window.customData = {
  "nsfwSubjects": [
    "Obsidian-Skinned Succubus Empress with molten-gold veins and glowing rune brands",
    "Living Latex Nun whose habit is her own fused second skin",
    "Tentacle-Corrupted Shrine Maiden with black sclera and writhing halo",
    "Porcelain Pleasure Android with exposed chrome joints and dripping synthetic arousal",
    "Crimson-Horned Demon Queen mid-orgasmic power surge",
    "Mind-Broken Angel with shattered halo and chains of light",
    "Bio-Luminescent Fertility Idol with glowing womb sigils",
    "High-Gloss Rubber Doll with permanent vacuum-sealed shine",
    "Corrupted Valkyrie dripping with black ichor and broken oaths",
    "Fleshcrafted Broodmother swollen with writhing offspring",
    "Oiled Amazonian War-Goddess glistening under arena lights",
    "Hypno-Spiral Priestess with vacant glowing eyes and drooling tongue",
    "Shibari-Wrapped Celestial Seraph suspended in glowing ropes",
    "Cum-Glazed Harem Slave with pearl strands across face and breasts",
    "Living Marionette with golden strings controlling every orgasm",
    "Vampire Countess mid-bloodfeeding ecstasy",
    "Dragon-Scale Dominatrix with smoke curling from nostrils",
    "Flesh-Warped Alchemist with extra lactating breasts and tentacles",
    "Gimp-Masked Pet-Play Kitten with diamond-studded collar and tail plug",
    "Glass-Encased Exhibition Doll in permanent display pose",
    "Nymphomaniac Wood-Elf with bark-patterned skin and dripping sap",
    "Chrome Succubus with mirrored skin reflecting every viewer",
    "Fallen Saint with stigmata that leak liquid gold",
    "Biomechanical Breeding Drone with exposed pistons and tubes",
    "Ahegao-Faced Oni Princess with tongue lolling and crossed eyes",
    "Slime-Infested Mermaid with translucent jelly skin",
    "Latex-Clad Corporate Succubus in skyscraper boardroom",
    "Gaping Void Priestess with black hole between thighs",
    "Tentacle Nest Dryad with living vines as hair",
    "Milking Farm Hucow with swollen udders and bell collar",
    "Corrupted Mermaid with lamprey mouth and bioluminescent lures",
    "Fleshcrafted Centaur with human torso and equine lower body in heat",
    "Living Sex Statue carved from marble that sweats and moans",
    "Demon-Possessed Nun mid-exorcism orgasm",
    "Cybernetic Geisha with holographic kimono and vibrating joints",
    "Gorgon with snakes that lactate venom",
    "Ice Demoness with frostbite nipples and frozen cum drips",
    "Fleshlight Golem with multiple functioning orifices",
    "Cum-Inflated Balloon Girl floating helplessly",
    "Living Gloryhole Wall with dozens of exposed holes",
    "Parasite-Infested Host with visible bulging movement under skin",
    "Wax-Play Candlemancer dripping molten wax from every orifice",
    "Flesh Puppet controlled by invisible master",
    "Oviposition Queen laying glowing eggs",
    "Lust-Crazed Werewolf mid-transformation orgasm",
    "Slutty Cherub with oversized adult features",
    "Cum-Drowned Mermaid in underwater breeding chamber",
    "Living Onahole Fairy small enough to fit in hand",
    "Brainwashed Cultist with mantra tattooed across body",
    "Eternal Orgasm Machine with permanent ahegao and convulsions"
  ],
  "nsfwActivityList": [
    "Being double-penetrated by massive demonic cocks",
    "Covered head-to-toe in thick layers of bukkake",
    "Suspended in complex glowing shibari while squirting uncontrollably",
    "Deepthroating a tentacle that pulses down her throat",
    "Riding a sybian until her eyes roll back permanently",
    "Fucked missionary while bound in a pentagram of chains",
    "Milked by mechanical pumps while moaning in ecstasy",
    "Gangbanged by shadow clones in endless mirror room",
    "Choking on cum while upside-down in 69 pile-driver",
    "Anally stretched by knotted canine cock mid-knot",
    "Fisted to the elbow while screaming in pleasure-pain",
    "Used as a urinal by circle of masked figures",
    "Oviposition: eggs being pushed deep inside womb",
    "Titfucked between breasts that lactate glowing fluid",
    "Edged for hours then forced to cum repeatedly",
    "Bound spread-eagle and vibrated to insanity",
    "Facefucked until mascara runs in black rivers",
    "Covered in wax while being fucked from behind",
    "Forced orgasm denial with ruined climax",
    "Inflated with cum until belly distends visibly",
    "Double anal with two massive demonic shafts",
    "Throat-bulge visible from brutal deepthroat",
    "Creampied consecutively by 20+ partners",
    "Nipples clamped and pulled while being fucked",
    "Electro-stimulated until convulsing in orgasm",
    "Fucked by machine with increasing speed settings",
    "Bound in latex vacuum bed, only holes exposed",
    "Used as living fleshlight by giant entity",
    "Tentacle gangbang filling every hole simultaneously",
    "Public use gloryhole with queue visible",
    "Bred repeatedly in fertility ritual",
    "Chained to wall and used as cum dumpster",
    "Forced to squirt in perfect arc frozen mid-air",
    "Nipple-fucked by tiny tentacles",
    "Womb tattoo glowing with each creampie",
    "Anally prolapsed and displayed proudly",
    "Covered in aphrodisiac slime that makes her beg",
    "Forced orgasms via magic wand torture",
    "Throat trained with progressively larger toys",
    "Used as breeding stock in demonic harem",
    "Cum inflation until translucent and sloshing",
    "Bound in stocks for public spanking and fucking",
    "Double vaginal penetration stretching to limit",
    "Lactation induced and sprayed in arcs",
    "Mind-broken from endless edging and denial",
    "Fucked while suspended in zero gravity",
    "Used as cum rag by entire orc warband",
    "Electro-ejaculation forced repeatedly",
    "Womb filled with glowing demonic seed",
    "Permanent ahegao from brain-melting pleasure"
  ],
  "nsfwExpressionList": [
    "Classic ahegao: eyes rolled back, tongue lolling, drool cascading",
    "Mind-broken vacant stare with heart-shaped pupils",
    "Cross-eyed orgasm with tears of joy streaming",
    "Screaming in silent ecstasy, mouth forming perfect O",
    "Begging with desperate puppy-dog eyes and trembling lips",
    "Post-orgasm blank face with drool string hanging",
    "Hypnotized spiral eyes and slack jaw",
    "Biting lip hard enough to draw blood in anticipation",
    "Eyes squeezed shut in overwhelming pleasure",
    "Tears of pure overwhelming ecstasy",
    "Feral snarl of dominance mid-thrust",
    "Glazed-over thousand-yard stare of total submission",
    "Tongue out panting like breeding bitch in heat",
    "Face frozen mid-squirt with perfect O-face",
    "Mascara running from facefucking tears",
    "Delirious smile of someone who’s cum too many times",
    "Vacant doll eyes with tiny hearts floating",
    "Pleading “more” with broken voice and crossed eyes",
    "Afterglow glow with half-lidded bedroom eyes",
    "Shocked wide eyes from sudden deep penetration",
    "Biting pillow to muffle screams",
    "Face buried in sheets from doggystyle pounding",
    "Looking up with worshipful cock-drunk eyes",
    "Tongue trying to catch flying cum mid-air",
    "Perfect heart-shaped ahegao pupils",
    "Face contorted in pain-pleasure from extreme stretch",
    "Drooling uncontrollably with tongue fully extended",
    "Eyes permanently crossed from brain-melting orgasm",
    "Smirk of cruel dominatrix mid-inflicting pain",
    "Broken smile of someone who’s accepted their role",
    "Face flushed crimson with arousal and shame",
    "Gasping for air between brutal thrusts",
    "Eyes glowing with demonic possession mid-climax",
    "Tears of humiliation mixing with tears of pleasure",
    "Face pressed against glass leaving steamy prints",
    "Permanent O-face frozen by magic",
    "Looking back with “destroy me” eyes",
    "Tongue curled in perfect ahegao spiral",
    "Face covered in cum with blissful closed eyes",
    "Shivering in aftershocks with twitching smile",
    "Eyes replaced by glowing runes during climax",
    "Mouth open in silent scream of release",
    "Face dripping with various fluids in perfect detail",
    "Worshipful gaze at the cock that owns her",
    "Eyes unfocused from too many ruined orgasms",
    "Smiling through gagged mouth and tears",
    "Face flushed and sweaty with hair stuck to cheeks",
    "Perfect broken doll expression",
    "Eyes rolling in different directions independently",
    "Ultimate ahegao: everything at maximum intensity"
  ],
  "nsfwBodyTypeList": [
    "Extreme hourglass with impossible 0.4 waist-to-hip ratio",
    "Permanently oiled and glistening hardbody",
    "Hyper-fertile breeding hips with visible glowing womb tattoo",
    "Latex-sealed second skin with zero imperfections or pores",
    "Absurdly shortstack with beach-ball sized breasts and ass",
    "Amazonian 7-foot muscle goddess with throbbing vascularity",
    "Morbidly obese BBW with rolls that jiggle hypnotically",
    "Anorexic waif with visible ribcage and protruding hip bones",
    "Cum-inflated belly permanently distended and sloshing",
    "Transparent skin revealing glowing demonic organs beneath",
    "Body covered in living, writhing erotic tattoos",
    "Extra rows of heavy lactating breasts down the torso",
    "Tentacle hair that constantly caresses and penetrates",
    "Body made of liquid mercury that ripples with every touch",
    "Functional gloryholes replacing nipples and navel",
    "Four fully articulated arms for maximum self-pleasure",
    "Long prehensile tail ending in a functioning pussy",
    "Hyper-pregnant with visible kicking and glowing runes",
    "Every inch pierced with rings, bars, and chains",
    "Skin permanently replaced with living black latex",
    "Massive thigh gap despite enormous fertile ass",
    "Body that phases through clothing when aroused",
    "Permanent goosebumps and perpetually erect nipples",
    "Skin that secretes thick aphrodisiac sweat",
    "Body temperature so high it visibly steams",
    "Glowing stretch marks from rapid sexual growth",
    "Body hair forming intricate erotic patterns",
    "Multiple functioning clits scattered across torso",
    "Back permanently arched in impossible pleasure curve",
    "Neck that rotates 360° during extreme deepthroat",
    "Three-foot prehensile tongue",
    "Pussy that visibly throbs, winks, and drools",
    "Ass cheeks that clap rhythmically on their own",
    "Breasts that lactate different fluids depending on mood",
    "Body covered in sensitive bioluminescent suckers",
    "Skin textured like wet, shiny latex at all times",
    "Visible heartbeat pulsing in oversized clit",
    "Skin that changes color with arousal level",
    "Permanent handprints and bruises in beautiful patterns",
    "Body that spins silk webs when horny",
    "Extra mouths in armpits, thighs, and breasts",
    "Skin that tastes and smells like honey and sin",
    "Pubic hair made of soft silk threads",
    "Nipples replaced with tiny wriggling tongues",
    "Asshole that blooms open like a flower when aroused",
    "Body covered in glowing runes during orgasm",
    "Skin that bruises into perfect floral patterns",
    "Body that spontaneously grows new erogenous zones",
    "Permanent tear tracks of pleasure down cheeks",
    "Entire body vibrates visibly when edged",
    "Flesh sculpted into perfect exaggerated fertility idol",
    "Bioluminescent veins pulsing under translucent skin",
    "Body that drips liquid gold when cumming",
    "Permanent ahegao-ready proportions and expression"
  ],
  "nsfwBreastList": [
    "Enormous, perfectly round breasts glistening with a thick layer of baby oil, catching dramatic rim-lighting",
    "Heavy, pendulous breasts hanging free, swaying hypnotically with every breath, veins faintly visible under translucent skin",
    "Breasts squeezed together by tight latex straps, deep cleavage dripping with sweat and cum glaze",
    "Nipples pierced with thick silver barbells connected by delicate chains to a matching collar",
    "Massive, gravity-defying breasts with glossy wet-look shine, nipples erect and dripping clear arousal fluid",
    "Pale, milky breasts covered in fresh red wax drippings that trace every curve",
    "Breasts bound in intricate red shibari rope, rope bite marks glowing against porcelain skin",
    "Huge lactating breasts actively spraying thin streams of glowing white milk in perfect arcs",
    "Nipples clamped with weighted clover clamps, stretched long and dark red from tension",
    "Breasts wrapped in transparent latex, nipples and areolas perfectly visible and pressed flat",
    "Perfect teardrop breasts with oversized puffy pink areolas, glistening under soft pink lighting",
    "Breasts covered in thick ropes of fresh semen that slowly drip down the underboob",
    "Dark, swollen areolas the size of silver dollars, nipples protruding like bullets",
    "Breasts pressed hard against glass, flattened and spreading with visible suction marks",
    "Nipples pierced with glowing neon rings that pulse with her heartbeat",
    "Underboob heavily shadowed, skin slick with sweat beads rolling down the curve",
    "Breasts encased in clear resin, nipples and veins perfectly preserved and magnified",
    "Huge, soft breasts with visible stretch marks glowing silver under blacklight",
    "Nipples leaking thick honey that runs in slow rivulets over the lower curve",
    "Breasts in a cupless latex bra, completely exposed and framed by glossy black straps",
    "Nipples covered in edible gold leaf that flakes off with every shuddering breath",
    "Breasts glistening with a mixture of saliva and precum, catching harsh key light",
    "Areolas textured like soft rose petals, flushed deep crimson from arousal",
    "Breasts wrapped in thin silver chains that dig into the flesh with every movement",
    "Nipples stretched by vacuum cups, swollen to twice their normal size",
    "Breasts covered in a lattice of thin red rope burns, skin flushed around each mark",
    "Nipples pierced with horizontal bars and tiny bells that jingle softly",
    "Huge, heavy breasts resting on a cold marble surface, nipples instantly hardening",
    "Breasts dripping with black latex paint that runs in perfect streaks",
    "Nipples adorned with tiny vibrating bullet toys, wires trailing down the torso",
    "Breasts glazed in thick, glossy syrup that catches and refracts studio strobes",
    "Pale breasts with faint blue veins visible just beneath the surface, nipples ice-hard",
    "Breasts bound so tightly the flesh bulges between crimson silk cords",
    "Nipples covered in shimmering diamond dust that sparkles with every tiny motion",
    "Huge, soft breasts with deep, dark areolas and pierced septum rings",
    "Breasts completely exposed through a shredded fishnet bodysuit, nipples poking through holes",
    "Nipples leaking glowing cyan fluid that traces bioluminescent trails down the skin",
    "Breasts covered in a thin layer of iridescent body oil that shifts color under light",
    "Nipples clamped and connected to a leash held tightly in her teeth",
    "Breasts glistening with a fresh layer of warm coconut oil, droplets suspended mid-drip",
    "Areolas tattooed with delicate black lace patterns that look real under flash",
    "Breasts pressed together by a thin leather harness, forming an impossibly deep valley",
    "Nipples pierced with thick gauge rings large enough to hook fingers through",
    "Breasts dripping with molten gold wax frozen mid-pour across the curves",
    "Huge, pendulous breasts swaying freely, nipples tracing lazy circles in the air",
    "Breasts covered in a sheer layer of silk so fine the texture of areolas shows through",
    "Nipples adorned with tiny ruby droplets that look like fresh blood",
    "Breasts glistening with a thick coating of clear silicone lube, hyper-realistic shine",
    "Areolas stretched wide and pale pink, nipples small and permanently inverted until aroused",
    "Breasts glistening with a perfect mixture of sweat and expensive perfume oil"
  ],
  "nsfwEffectList": [
    "Perfect cinematic lens flares kissing every wet highlight and droplet",
    "Golden hour sunbeams piercing through suspended droplets of arousal",
    "Tiny glowing butterflies made of pure light circling the clit",
    "Iridescent oil slicks rippling across skin in shifting rainbow colors",
    "Soft pink pheromone mist swirling lazily around hips and breasts",
    "Delicate cherry blossom petals landing on glistening wet skin and sticking",
    "Glowing particles of magic dust settling on exposed clit",
    "Microscopic glitter mixed with cum sparkling under studio strobes",
    "Golden champagne bubbles rising from between spread legs",
    "Tiny glowing fireflies circling erect nipples like a halo",
    "Translucent bubbles of milk lazily rising from pierced nipples",
    "Liquid gold leaf fragments drifting and sticking to oiled skin",
    "Soft pastel smoke curling from between spread legs",
    "Warm steam rising gently from between trembling thighs",
    "Tiny heart-shaped bokeh flares dancing in the background",
    "Fine powder of edible gold dusting across glistening cleavage",
    "Golden wax droplets frozen mid-fall across bare breasts",
    "Slow-motion water droplets rolling down the curve of an arched back",
    "Soft white feathers drifting through beams of dramatic side-light",
    "Gossamer-thin strands of glowing spiderweb catching soft backlight",
    "Delicate lace fragments torn and drifting in slow motion",
    "Soft pink sakura petals soaked in milk drifting across the scene",
    "Floating translucent veils of spider silk clinging to sweat-slick curves",
    "Micro-confetti of diamond dust exploding outward on final climax",
    "Tiny luminous jellyfish-like orbs hovering around lactating breasts",
    "Soft crimson silk ribbons untied and floating weightlessly around the body",
    "Iridescent soap bubbles filled with glowing cum floating upward",
    "Delicate crystal shards of shattered chastity belt suspended mid-air",
    "Thin streams of honey dripping in perfect parabolic curves",
    "Warm honey droplets hovering like golden fireflies",
    "Soft lavender fog curling around pierced nipples",
    "Gentle snowflakes melting instantly on overheated skin",
    "Slow-motion black rose petals falling and sticking to wet lips",
    "Slow-motion rose petals soaked in fresh semen drifting across the frame",
    "Thick cum droplets suspended mid-air, catching golden rim light like floating pearls",
    "Glistening strings of arousal fluid stretching and snapping in perfect viscous arcs",
    "Tiny glowing embers of lust floating upward from flushed skin",
    "Fine silk threads of saliva connecting tongue to floor in slow motion",
    "Warm candle-wax droplets hovering mid-air before landing on skin",
    "Floating veil of sheer white lace dissolving into mist",
    "Delicate bubbles of aphrodisiac perfume popping against bare flesh",
    "Tiny glowing spores of lust drifting from open mouth",
    "Soft white down feathers coated in fresh cream drifting downward",
    "Translucent silk ribbons unraveling and floating in zero gravity",
    "Warm breath condensation forming perfect little clouds in cold air",
    "Slow-falling black latex droplets splattering across pale skin",
    "Tiny glowing runes materializing and fading on sweat-slick skin",
    "Fine mist of expensive perfume mixing with visible pussy scent",
    "Floating translucent latex bubbles popping against bare ass",
    "Soft white feathers drifting down, some stuck to wet thighs and breasts"
  ],
  "background": [
    "majestic marble palace hall with 50-foot gold-inlaid ceilings and rose-petal-strewn floors",
    "moonlit enchanted forest clearing ringed by ancient glowing oaks",
    "grand rococo ballroom lit by a thousand floating crystal chandeliers",
    "sunrise atop a mist-shrouded mountain temple of white jade",
    "opulent Ottoman throne room with silk cushions and rosewater fountains",
    "twilight rose garden labyrinth under a sky of falling petals",
    "ancient elven tree-palace woven from living silver branches",
    "golden autumn cathedral of stained glass and drifting maple leaves",
    "baroque Venetian masquerade balcony overlooking moonlit canals",
    "snowbound ice palace with aurora borealis streaming through crystal walls",
    "lavish Persian harem bathed in soft lantern light and incense smoke",
    "cherry-blossom shrine atop a cliff with endless pink petals in the wind",
    "gothic cathedral interior with shafts of colored light and drifting incense",
    "sun-drenched Mediterranean courtyard with marble fountains and climbing wisteria",
    "floating sky palace of white marble suspended among pastel clouds",
    "secret moonlit lagoon surrounded by bioluminescent lilies",
    "imperial Chinese palace garden during lantern festival",
    "victorian greenhouse overflowing with exotic orchids and soft fog",
    "ancient Greek temple at sunset with marble columns glowing orange",
    "grand library with endless towering bookshelves and floating candlelight",
    "crystal cavern palace lit from within by glowing geodes",
    "misty bamboo grove with stone lanterns and gentle rain",
    "lavish art-nouveau boudoir with peacock-feather walls and velvet",
    "starlit desert oasis palace with silk tents and silver moonlight",
    "frost-covered winter rose conservatory under northern lights",
    "floating lantern-lit lake with thousands of glowing paper boats",
    "baroque opera house stage with crimson curtains and golden proscenium",
    "ancient Celtic stone circle under a sky of shooting stars",
    "sunlit meadow of wildflowers with distant snow-capped mountains",
    "grand marble staircase descending into a mirror-still underground lake",
    "twilight lavender fields stretching to a distant fairy-tale castle",
    "abandoned renaissance palace overgrown with flowering vines",
    "golden-hour vineyard terrace overlooking rolling hills",
    "serene lotus pond palace with golden pagodas reflected perfectly",
    "moon bridge over koi pond in perfect cherry-blossom snowfall",
    "opulent Byzantine basilica with golden mosaics and candlelight",
    "whimsical fairy-tale castle bedroom with four-poster bed and starlight ceiling",
    "ancient Egyptian hypostyle hall with lotus columns and torchlight",
    "autumn forest palace made entirely of stained-glass leaves",
    "cliffside monastery library overlooking endless sea and sunset",
    "secret garden behind ivy-covered walls with a single glowing fountain",
    "grand Venetian palazzo interior with frescoed ceilings and candlelit canals visible",
    "imperial Japanese palace during full-moon viewing ceremony",
    "enchanted swan lake at midnight with silver mist and glowing swans",
    "baroque mirror gallery reflecting infinite chandeliers",
    "sunrise over Kyoto temple roofs blanketed in cherry blossoms",
    "lavish Rajasthani palace courtyard with peacocks and marble jali screens",
    "ancient Druid grove with standing stones and fireflies",
    "crystal greenhouse atop a floating island with waterfalls into clouds",
    "moonlit gothic graveyard with marble angels and soft fog",
    "Persian rosewater palace with reflecting pools and silk canopies",
    "grand marble atrium with a glass dome full of drifting petals",
    "twilight ice cavern palace with frozen waterfalls and soft blue light",
    "abandoned opera house with velvet seats and floating dust motes in spotlight",
    "golden desert palace at sunset with endless dunes and silk banners",
    "secret rooftop garden in an ancient city with star-filled sky",
    "victorian conservatory filled with white roses and morning mist",
    "ancient library of Alexandria reborn with floating scrolls and soft torchlight",
    "emerald bamboo palace hidden in perpetual gentle rain",
    "grand marble bathhouse with rose petals floating on steaming water",
    "forbidden palace rooftop under fireworks and full moon",
    "enchanted winter ballroom with ice sculptures and soft snowfall indoors",
    "lavish Mughal palace with jewel-toned mosaics and fountains",
    "moonlit Mediterranean cliff villa with infinity pool and jasmine",
    "ancient celestial observatory with star maps painted on domed ceiling",
    "fairytale forest throne made of living roots and glowing mushrooms",
    "opulent vampire castle great hall with crimson velvet and candlelight",
    "serene Shinto shrine covered in fresh snow and red torii gates",
    "grand baroque fountain courtyard with statues and perfect symmetry",
    "hidden tropical waterfall palace with orchids cascading down stone",
    "luxury penthouse terrace overlooking cyber-city at golden hour",
    "futuristic glass palace floating above clouds at sunset",
    "neon-lit rooftop garden 100 stories up with soft rain",
    "high-tech greenhouse with holographic butterflies and real flowers",
    "cyberpunk palace interior with floor-to-ceiling hologram windows",
    "floating maglev train interior with panoramic sunset views",
    "futuristic marble hall with gentle floating data-orbs",
    "sleek luxury yacht deck at night with city skyline reflection",
    "minimalist sky-lounge with transparent floor and stars beneath",
    "cyber-cathedral with stained-glass holograms and soft light",
    "rooftop infinity pool reflecting neon city and full moon",
    "ultra-modern palace atrium with gentle floating lanterns and water features"
  ],
  "breastTypeList": [
    "delicate rosebud breasts with soft pink areolas barely visible beneath sheer silk",
    "graceful teardrop curves gently rising with each breath",
    "full, perfectly rounded breasts that catch golden hour light like polished marble",
    "petite, pert breasts crowned with tiny coral-pink buds",
    "elegant C-cup swells framed by delicate lace and morning mist",
    "soft, natural handfuls nestled in embroidered velvet",
    "slender aristocratic chest with subtle, regal curves",
    "generous yet weightless breasts floating beneath gossamer fabric",
    "small, high-set breasts like fresh spring blossoms",
    "pale moonlit cleavage traced by a single strand of pearls",
    "warm sun-kissed curves peeking through climbing ivy",
    "modest A-cup treasures hidden beneath layers of antique lace",
    "supple, youthful breasts rising proudly beneath a silk kimono",
    "soft hourglass swells cradled in silver filigree armor",
    "delicate porcelain décolletage dusted with gold powder",
    "full, maternal curves draped in flowing white linen",
    "gentle, athletic breasts with faint tan lines from summer armor",
    "elegant B-cup silhouette beneath translucent crystal gown",
    "soft, romantic swells framed by cascading rose petals",
    "pale alabaster chest with the faintest blush of pink",
    "graceful, dancer’s breasts that move like water beneath satin",
    "modest yet perfectly shaped beneath a high-necked victorian gown",
    "warm, honey-toned cleavage glowing in candlelight",
    "small, proud breasts adorned with a single sapphire pendant",
    "lush, natural D-cup curves barely contained by corseted velvet",
    "ethereal, almost weightless breasts under starlight and moonlight silk",
    "soft, dewy cleavage kissed by morning mist in the garden",
    "elegant swells traced by delicate gold body chains",
    "petite, flower-like breasts peeking through cherry blossoms",
    "regal, statuesque chest rising beneath royal ermine and jewels",
    "gentle, feminine curves beneath hand-embroidered linen",
    "slender elven chest with subtle, silvery undertones",
    "warm, sun-ripened breasts framed by tropical flowers",
    "soft, romantic bosom rising and falling beneath antique lace",
    "pale winter breasts dusted with the finest powdered sugar snow",
    "graceful, aristocratic swells beneath a high collar of white fox",
    "full, natural curves cradled in soft moss and morning light",
    "delicate, ballerina breasts beneath layers of pale tulle",
    "modest yet impossibly perfect beneath a simple linen shift",
    "soft, moonlit cleavage traced by silver filigree and starlight",
    "elegant handfuls nestled in black velvet and white pearls",
    "gentle, wind-kissed curves beneath flowing meadow silk",
    "pale, porcelain chest adorned with a single red camellia",
    "supple, youthful swells beneath translucent rice-paper screens",
    "soft, romantic breasts framed by climbing wisterWith wisteria at dusk",
    "graceful, high-set curves beneath a gown of liquid moonlight",
    "warm, golden-hour cleavage glowing beneath strands of amber",
    "delicate, barely-there breasts beneath layers of spider-silk veil",
    "lush, natural bosom rising proudly beneath forest-green velvet",
    "elegant, timeless curves that belong in an oil painting masterpiece"
  ],
  "shotList": [
    "intimate extreme close-up on eyes and parted lips",
    "perfect full-body composition with leading lines to subject",
    "delicate waist-up portrait framed by soft window light",
    "dramatic low-angle hero shot from marble floor",
    "elegant three-quarter view with gentle contraposto",
    "romantic over-the-shoulder shot with flowing hair in foreground",
    "ethereal silhouette against golden-hour sky",
    "graceful kneeling pose filling the lower third",
    "dynamic dutch-tilt full body with swirling petals",
    "soft upper-body shot bathed in rim lighting",
    "majestic wide shot with subject tiny against grand architecture",
    "intimate macro of hands and collarbone",
    "cinematic profile view with dramatic side-lighting",
    "elegant back view with long hair cascading down spine",
    "poetic close-up of décolletage and necklace",
    "powerful worm’s-eye view looking straight up at subject",
    "serene overhead shot with subject lying in flowers",
    "romantic medium shot with shallow negative space",
    "regal throne shot from the foot of marble stairs",
    "dreamy extreme wide shot with tiny subject in vast landscape",
    "tender close-up of clasped hands and subtle cleavage",
    "dynamic action pose frozen mid-twirl",
    "soft-focus portrait with subject in lower right third",
    "epic symmetrical composition with subject dead center",
    "gentle seated portrait with crossed legs and soft smile",
    "intimate bed shot from above with silk sheets",
    "dramatic chiaroscuro half-body lit by single candle",
    "elegant fashion-magazine cover pose",
    "fairytale storybook illustration framing",
    "perfect rule-of-thirds full-length with sunset backdrop",
    "eye-level intimate gaze",
    "low heroic angle from ground",
    "high regal angle from balcony",
    "subtle dutch tilt for tension",
    "extreme worm’s-eye beneath flowing gown",
    "bird’s-eye straight down",
    "soft 45-degree fashion angle",
    "perfect profile against light",
    "gentle over-the-shoulder",
    "backlit silhouette angle",
    "slight low-angle three-quarter",
    "high-angle looking down marble staircase",
    "cinematic side-light profile",
    "dramatic top-down spiral staircase",
    "soft front-light beauty angle",
    "45-degree dutch for dreamlike feel",
    "extreme high-angle tiny figure in grand hall",
    "intimate close-up low angle",
    "regal straight-on throne angle",
    "poetic back-view angle",
    "gentle 30-degree fashion tilt",
    "dynamic contra-post angle",
    "soft overhead bridal veil angle",
    "powerful centered symmetrical angle",
    "romantic three-quarter beauty angle",
    "subtle high-angle garden shot",
    "elegant 60-degree side angle",
    "dreamy 15-degree tilt",
    "perfect golden-ratio offset angle",
    "classic straight-on portrait angle",
    "perfect rule-of-thirds placement",
    "dead-center symmetrical framing",
    "leading lines drawing eye to subject",
    "natural frame of archway or window",
    "negative space masterpiece",
    "golden ratio spiral composition",
    "soft vignette drawing focus inward",
    "framed by flowing hair and fabric",
    "environmental portrait with context",
    "tight beauty framing",
    "grand wide establishing frame",
    "diagonal dynamic composition",
    "circular framing with arms or architecture",
    "layered depth with foreground elements",
    "minimalist centered frame",
    "off-center mysterious framing",
    "framed by cherry-blossom branches",
    "perfect square instagram composition",
    "cinematic letterbox bars",
    "framed between marble columns",
    "soft triangular composition",
    "balanced two-subject framing",
    "vertical portrait orientation",
    "horizontal landscape orientation",
    "framed by candlelight and shadows",
    "dreamlike double-exposure framing",
    "framed by silk curtains and light beams",
    "elegant fashion-magazine crop",
    "storytelling environmental frame",
    "perfectly balanced symmetrical frame"
  ],
  "cameraLensList": [
    "85mm creamy bokeh portrait lens",
    "50mm natural perspective",
    "35mm environmental storytelling lens",
    "135mm telephoto compression",
    "24mm dramatic wide-angle",
    "85mm f/1.2 razor-thin depth",
    "50mm f/1.4 dreamy glow",
    "35mm f/1.8 soft corners",
    "100mm macro intimate details",
    "24-70mm versatile zoom",
    "70-200mm beautiful compression",
    "prime 50mm classic look",
    "vintage Helios swirly bokeh",
    "anamorphic cinematic oval bokeh",
    "petzval lens artistic swirl",
    "tilt-shift miniature effect",
    "soft-focus dream lens",
    "ultra-sharp modern 85mm",
    "vignetting vintage lens",
    "cinematic 40mm pancake",
    "fish-eye dramatic curve",
    "medium-format look",
    "large-format softness",
    "Zeiss milvus clinical sharpness",
    "Cooke look warm and glowing",
    "Canon L-series luxury rendering",
    "Sony G-master perfection",
    "Leica APO summicron magic",
    "Voigtländer nokton character",
    "sigma art ultimate sharpness",
    "razor-thin depth of field, only eyes in focus",
    "creamy f/1.2 bokeh blur",
    "buttery smooth background separation",
    "dreamy f/2.8 swirl",
    "sharp f/8 full-body clarity",
    "ethereal f/1.4 glow",
    "cinematic anamorphic bokeh",
    "swirly petzval background",
    "perfect subject isolation",
    "soft f/2 foreground and background blur",
    "ultra-shallow depth with glowing highlights",
    "medium depth f/5.6 environmental sharpness",
    "deep depth f/11 everything crisp",
    "selective focus on lips only",
    "bokeh balls dancing in background",
    "foreground bokeh framing subject",
    "pin-sharp eyes, everything else melts",
    "gentle f/4 softness",
    "dreamlike lens blur",
    "macro-level thin depth",
    "hyperfocal landscape sharpness",
    "tilt-shift selective focus",
    "breathing background blur",
    "silky f/1.8 transition",
    "clinical f/2 sharpness on subject",
    "romantic f/2.8 fall-off",
    "fairytale bokeh orbs",
    "velvety background melt",
    "perfect isolation at f/1.2"
  ],
  "lookalikeList": [
    "Timeless beauty of Monica Bellucci in her prime",
    "Audrey Hepburn elegant breakfast-at-tiffany’s grace",
    "Marilyn Monroe 1950s bombshell glow",
    "Young Brigitte Bardot sun-kissed French riviera",
    "Natalie Portman Black Swan ballerina intensity",
    "Anya Taylor-Joy chess-queen porcelain doll features",
    "Margot Robbie Harley-Quinn playful madness",
    "Scarlett Johansson Black Widow hourglass perfection",
    "Gal Gadot Wonder Woman regal amazonian strength",
    "Zendaya ethereal dune-princess cheekbones",
    "Ana de Armas Bond-girl Cuban fire",
    "Sydney Sweeney modern bombshell innocence",
    "Alexandra Daddario piercing Greek-goddess blue eyes",
    "Emma Watson Hermione-turned-red-carpet elegance",
    "Florence Pugh soft English rose with edge",
    "Jenna Ortega Wednesday Addams dark beauty",
    "Classic Angelina Jolie Lara Croft era lips and danger",
    "Keira Knightley period-drama aristocratic bone structure",
    "Kate Beckinsale Underworld vampire queen sharpness",
    "Charlize Theron atomic blonde ice-queen perfection",
    "Rosamund Pike gone-girl chilling beauty",
    "Eva Green 300 Persian sorceress mystique",
    "Salma Hayek Frida painter passion",
    "Penélope Cruz Spanish flamenco fire",
    "Deepika Padukone Bollywood royal elegance",
    "Fan Bingbing Chinese empress regal presence",
    "Aishwarya Rai classic Indian goddess features",
    "Priyanka Chopra modern global queen energy",
    "Gemma Chan minimalist futuristic beauty",
    "Liu Yifei Mulan ethereal Chinese fairy",
    "Song Hye-kyo Korean drama soft perfection",
    "IU K-pop angel-faced Korean idol",
    "Lisa Blackpink Thai dancer sharpness",
    "Jennie Blackpink Parisian chic attitude",
    "Irene Red Velvet Korean ice princess",
    "Taehyung BTS androgynous flower-boy beauty",
    "Jungkook golden maknae soft masculinity",
    "Classic anime heroine with huge expressive eyes",
    "Studio Ghibli princess soft watercolor aesthetic",
    "Alphonse Mucha art-nouveau muse",
    "John William Waterhouse pre-raphaelite nymph",
    "Gustav Klimt golden portrait goddess",
    "William-Adolphe Bouguereau classical porcelain beauty",
    "Leonardo da Vinci Mona Lisa enigmatic smile",
    "Botticelli Venus ethereal Renaissance ideal",
    "Caravaggio dramatic chiaroscuro beauty",
    "Vermeer girl with a pearl earring soft light",
    "Frida Kahlo unibrow and flowers intensity",
    "Tamara de Lempicka art-deco sharp glamour",
    "Amedeo Modigliani elongated neck elegance",
    "Pablo Picasso cubist muse intensity",
    "Henri Matisse fauvist color goddess",
    "Yayoi Kusama polka-dot infinity queen",
    "Anime-style Makoto Shinkai heroine with comet hair",
    "Kyoto Animation soft moe angel",
    "90s Sailor Moon transformation elegance",
    "Neon Genesis Evangelion Rei Ayanami clone mystery",
    "Cyberpunk 2077 V female sharp beauty",
    "Final Fantasy Tifa Lockhart compassionate strength",
    "Lara Croft Tomb Raider reborn realistic beauty",
    "Princess Zelda breath of the wild royal softness",
    "Bayonetta witch-with-glasses dominatrix elegance",
    "2B Nier Automata blindfolded android grace",
    "Ciri Witcher wild hunt scar and silver hair"
  ],
  "femaleUpperBody": [
    "nothing but a thin silver body chain draped across bare breasts",
    "completely topless, only diamond pasties covering nipples",
    "micro latex bralette that barely covers areolas",
    "transparent mesh crop top with no bra underneath",
    "open-cup leather harness framing exposed breasts",
    "sheer black lace bodysuit with strategic cutouts over nipples",
    "fishnet crop top shredded to ribbons",
    "cupless corset pushing breasts up and fully exposed",
    "wet white t-shirt clinging transparently to bare chest",
    "only a thick leather collar and matching nipple clamps",
    "body painted with liquid latex, nipples visibly hard",
    "tiny triangle bikini top pulled aside",
    "open-front latex bolero jacket, breasts completely bare",
    "nipple piercings connected by delicate silver chain",
    "see-through vinyl raincoat worn open",
    "bandage wrap top deliberately loose and slipping",
    "glossy black tape X pasties only",
    "strappy bondage harness with breasts fully out",
    "sheer babydoll crop with underboob spilling free",
    "metallic chainmail bikini top missing half the links",
    "pasties made of dripping wet rose petals",
    "open blazer with nothing underneath, lapels framing bare breasts",
    "body harness of thin red rope biting into pale skin",
    "wet-look micro crop top rolled up under breasts",
    "clear PVC bralette with visible nipple rings",
    "leather shelf bra presenting breasts like an offering",
    "torn fishnet long-sleeve with massive chest holes",
    "only a velvet choker and dripping body oil",
    "latex micro suspenders framing bare torso",
    "open-cup satin bustier with breasts proudly displayed",
    "body chain and nipple barbells only",
    "sheer white crop top soaked and 100% transparent",
    "gloved arms and nothing covering the chest",
    "black electrical tape in perfect X across nipples",
    "wet silk blouse unbuttoned and clinging to bare skin",
    "open-front chain top dangling across exposed breasts",
    "nipple tassels swinging freely",
    "transparent latex crop top with built-in nipple cutouts",
    "body harness of glowing neon straps, breasts fully bare",
    "micro bandeau slipped down beneath breasts",
    "only a leather waist cincher pushing breasts upward",
    "clear plastic bralette with nothing underneath",
    "shredded crop top hanging in tatters off shoulders",
    "body oil and a single strategically placed hand",
    "open-cup quarter bra with underboob and sideboob exposed",
    "wetlook mesh bodysuit ripped open at the chest",
    "pasties shaped like tiny hearts, barely covering anything",
    "leather X harness and nothing else on torso",
    "see-through lace bralette with nipples visibly pierced",
    "open satin robe sliding off shoulders revealing everything",
    "body chain mail that covers absolutely nothing important"
  ],
  "lightingList": [
    "-None-",
    "dramatic golden-hour sunset piercing through silk curtains",
    "soft volumetric god rays cutting through incense smoke",
    "harsh neon cyberpunk pink and teal glow",
    "single overhead spotlight in an otherwise pitch-black void",
    "warm flickering candlelight casting long dancing shadows",
    "cold blue moonlight spilling across marble floors",
    "crimson demonic rim-lighting with glowing rune edges",
    "soft pastel dawn light filtered through cherry blossoms",
    "harsh white studio strobes with hard shadows",
    "gentle firefly glow in an enchanted midnight forest",
    "golden cinematic lens flares kissing every curve",
    "deep teal and orange cyber-noir streetlight bleed",
    "warm honey-colored rim light tracing every oiled contour",
    "soft lavender fog lit from beneath by hidden LEDs",
    "dramatic chiaroscuro with one beam of light on bare skin",
    "blood-red backlight making skin glow like molten glass",
    "ethereal bioluminescent underwater cyan glow",
    "harsh overhead surgical light in a dark dungeon",
    "soft rosy bedroom lamp glow on silk sheets",
    "golden baroque chandelier light dripping from above",
    "icy blue aurora borealis streaming through crystal walls",
    "warm amber firelight flickering across bare breasts",
    "neon purple club lighting with pulsing bass strobes",
    "soft golden renaissance window light like an oil painting",
    "cold sterile white light in a futuristic latex chamber",
    "warm steam-filled bathhouse light through rising mist",
    "deep crimson hellfire backlighting with smoke tendrils",
    "soft peach sunrise light through gauze curtains",
    "harsh interrogation spotlight from directly above",
    "gentle candlelit gothic cathedral shafts of colored light",
    "electric blue holographic light dancing across skin",
    "warm vintage Hollywood key light with velvet shadows",
    "soft pink pheromone haze lit from within",
    "icy moonlight through broken stained-glass windows",
    "golden desert sunset casting long dramatic shadows",
    "soft green absinthe fairy light in a dark speakeasy",
    "harsh white flash photography mid-climax freeze",
    "deep purple velvet club lighting with laser grids",
    "warm honey-dripping afternoon light through venetian blinds",
    "cold clinical LED strips in a black latex room",
    "soft rose-gold sunset through floor-to-ceiling windows",
    "demonic red rim light with glowing pentagram floor",
    "gentle snowfall lit by distant castle torches",
    "warm oil-lamp glow in an ancient harem tent",
    "sharp cyan cyberpunk rain reflections on skin",
    "soft golden bokeh fairy lights floating in darkness",
    "harsh overhead red safe-light in a darkroom",
    "warm caramel candlelight dripping down bare back",
    "cold midnight blue light with visible starfield through dome",
    "soft pastel cotton-candy club lighting with glitter reflections"
  ],
  "qualityList": ["insane details, intricate linework, hypermaximalist masterpiece",
"god-tier resolution, razor-sharp clarity, crystalline precision",
"filigree carved by master artisans, baroque ornamentation, obsessive craftsmanship",
"16k RAW perfection, 32k ultimate fidelity, breathtaking visual density",
"flawless execution, museum-worthy grandeur, award-winning composition",
"golden ratio perfection, divine proportions, mathematically perfect balance",
"photorealistic masterpiece, hyperrealistic beyond belief, lifelike transcendence",
"skin textured to perfection, microscopic pore detail, velvet-smooth realism",
"individual hair strands rendered, flowing with natural luster, hyper-detailed fibers",
"eyes with galactic depth, sparkling reflections, soul-piercing clarity",
"musculature sculpted like classical statues, perfect anatomy, heroic definition",
"dynamic heroic pose, cinematic motion frozen in time, epic action mastery",
"volumetric godrays piercing the heavens, golden light shafts, divine illumination",
"ethereal atmospheric haze, dreamy depth, cinematic environmental beauty",
"dramatic chiaroscuro lighting, masterful contrast, Rembrandt-level shadows",
"creamy bokeh masterpiece, buttery background blur, professional depth of field",
"ray-traced reflections, mirror-like surfaces, physically accurate shine",
"global illumination perfection, studio-quality lighting, flawless light bounce",
"prismatic highlights exploding, radiant specular detail, luminous brilliance",
"deep velvety shadows, rich tonal range, cinematic darkness control",
"vibrant yet natural colors, perfectly balanced palette, artistic color harmony",
"overwhelming visual richness, detail density that defies logic, sensory overload",
"rule of thirds perfection, impeccable framing, professional composition mastery",
"monumental scale and presence, epic grandeur, awe-inspiring proportions",
"zero artifacts, zero flaws, zero compromises",
"render so perfect it redefines excellence, masterpiece that transcends time, ultimate visual achievement",
"microscopic surface detail, tactile realism, luxurious textural depth",
"jewel-like clarity and sparkle, gemstone-level precision, radiant refinement",
"flowing fabric with perfect folds, intricate clothing detail, textile realism",
"dynamic wind-swept motion, dramatic energy, frozen moment of power",
"studio lighting perfection, soft yet dramatic, professional portrait quality",
"atmospheric perspective mastery, infinite depth, realistic distance rendering",
"award-winning digital painting, trending worldwide, critically acclaimed artwork",
"hyper-detailed background elements, fully realized environment, immersive world-building",
"perfect hands and fingers, anatomically flawless, no deformities ever",
"expressive facial detail, emotive eyes, character depth that tells stories",
"insanely sharp focus, tack-sharp throughout, professional lens quality",
"rich color grading, cinematic tones, Hollywood-level post-processing",
"epic fantasy atmosphere, majestic presence, legendary visual impact",
"intricate armor engravings, ornate weapon detail, masterwork craftsmanship",
"flowing energy effects, glowing aura, magical yet realistic light",
"perfect symmetry when needed, intentional asymmetry when artistic, compositional genius",
"breath-taking panoramic scale, vast landscapes, infinite horizon detail",
"subtle skin imperfections for realism, natural beauty enhanced, authentic humanity",
"dynamic camera angle, dramatic perspective, perfectly chosen viewpoint",
"insane particle effects, floating dust motes, atmospheric scattering perfection",
"ultimate textural variety, every material distinct, visual encyclopedia of surfaces",
"timeless masterpiece quality, heirloom-level artwork, eternal visual legacy",
"zero noise, zero blur, zero mediocrity allowed",
"the pinnacle of digital art, the absolute ceiling of quality, perfection incarnate"]

};
