window.customData = {
    "subjectTypeList": [
        "-None-",
        "A breathtaking 32k cinematic masterpiece photograph of",
        "An epic IMAX 70mm film still of",
        "A hyperrealistic 16k RAW professional studio portrait of",
        "A dramatic National Geographic cover shot of",
        "A larger-than-life cinematic close-up of",
        "An ultra-detailed Vogue India editorial photograph of",
        "A majestic 8k hyperrealistic fashion campaign image of",
        "A breathtaking cinematic beauty shot of",
        "A god-tier photorealistic magazine cover of",
        "An award-winning cinematic portrait of",
        "A hyper-detailed 32k commercial advertising shot of",
        "A stunning Bollywood movie poster still of",
        "A flawless 16k cinematic red-carpet photograph of",
        "A jaw-dropping hyperrealistic beauty campaign of",
        "A cinematic masterpiece film frame of",
        "An ultra-sharp 32k luxury fashion editorial of",
        "A photorealistic cinematic blockbuster scene of",
        "A breathtaking 8k beauty portrait of",
        "A dramatic high-fashion cinematic shot of",
        "A hyperrealistic 16k beauty close-up of",
        "An epic cinematic hero portrait of",
        "A stunning 32k photorealistic advertisement of",
        "A larger-than-life IMAX character portrait of",
        "A flawless Vogue cinematic cover of",
        "A hyper-detailed 16k cinematic beauty shot of",
        "An ultra-realistic National Film Awards portrait of",
        "A breathtaking 32k cinematic drama still of",
        "A god-tier 8k hyperrealistic fashion photograph of",
        "A cinematic masterpiece close-up portrait of",
        "A dramatic 16k luxury brand campaign of",
        "An epic Bollywood cinematic frame of",
        "A flawless 32k photorealistic beauty image of",
        "A hyperrealistic IMAX character shot of",
        "A stunning 16k cinematic red-carpet moment of",
        "A breathtaking Vogue India cinematic cover of",
        "An ultra-detailed 32k commercial portrait of",
        "A cinematic blockbuster hero shot of",
        "A god-tier 8k hyperrealistic editorial of",
        "A flawless 16k beauty campaign photograph of",
        "A dramatic 32k cinematic masterpiece of",
        "An epic National Geographic cinematic portrait of",
        "A hyperrealistic 16k luxury fashion shot of",
        "A breathtaking 8k cinematic beauty portrait of",
        "A stunning IMAX film still of",
        "A flawless Vogue cinematic editorial of",
        "An ultra-sharp 32k beauty close-up of",
        "A cinematic masterpiece character portrait of",
        "A hyper-detailed 16k red-carpet photograph of",
        "A god-tier 32k photorealistic campaign of",
        "A breathtaking 8k cinematic drama portrait of",
        "An epic 16k Bollywood movie still of",
        "A flawless 32k luxury brand image of",
        "A dramatic IMAX cinematic hero shot of",
        "A hyperrealistic 16k beauty editorial of",
        "A stunning 32k cinematic cover photograph of",
        "A breathtaking National Filmfare portrait of",
        "An ultra-detailed 8k cinematic blockbuster frame of",
        "A god-tier 32k hyperrealistic beauty shot of",
        "A flawless 16k Vogue India editorial of",
        "A cinematic masterpiece 32k portrait of",
        "A breathtaking 16k luxury campaign of",
        "An epic 8k cinematic red-carpet shot of",
        "A hyperrealistic IMAX character portrait of",
        "A stunning 32k photorealistic beauty image of",
        "A flawless 16k cinematic drama still of",
        "A dramatic 32k National Geographic cover of",
        "A god-tier 8k hyperrealistic fashion portrait of",
        "A breathtaking 16k cinematic masterpiece of",
        "-Finish-"
    ],
	
    "maleSubjects": [
        "-None-",
        "Towering Rajput warrior king",
        "Stern Sikh regiment commander",
        "Ancient Vedic rishi with sacred thread",
        "Modern Mumbai billionaire industrialist",
        "Fierce Maratha cavalry general",
        "Royal Mughal emperor on throne",
        "Traditional Kathakali dancer in full makeup",
        "Powerful Gurkha soldier with kukri",
        "Sophisticated Delhi diplomat",
        "Spiritual Sadhu with trishul and damaru",
        "Ancient Chola bronze warrior king",
        "Modern Indian Navy admiral",
        "Tribal Naga warrior with spear",
        "Royal Hyderabadi nawab in sherwani",
        "Fierce Rajasthani bandit king",
        "Contemporary Bollywood megastar",
        "Ancient Mauryan emperor Ashoka",
        "Powerful Punjabi folk singer",
        "Graceful Manipuri martial artist",
        "Opulent Jaipur palace maharaja",
        "Modern Indian cricketing legend",
        "Spiritual Himalayan yogi master",
        "Fierce Pathan warrior with rifle",
        "Royal Mysore Wodeyar king",
        "Ancient Vedic fire priest",
        "Powerful Bengali revolutionary",
        "Traditional Theyyam performer god",
        "Modern Indian Air Force fighter pilot",
        "Tribal Gond warrior with axe",
        "Royal Cochin maharaja in gold",
        "Fierce Jat farmer warrior",
        "Spiritual Baul mystic singer",
        "Ancient Vijayanagara emperor",
        "Powerful Indian Army general",
        "Graceful Odissi male dancer",
        "Modern Indian tech billionaire",
        "Royal Mewar Rana with sword",
        "Fierce Northeast tribal hunter",
        "Spiritual Jain monk in white",
        "Ancient Indus Valley bearded priest",
        "Powerful Haryanvi wrestler",
        "Traditional Yakshagana warrior king",
        "Modern Indian space scientist",
        "Royal Travancore maharaja",
        "Fierce Bhil tribal archer",
        "Spiritual Sufi qawwal master",
        "Ancient Pallava rock-cut king",
        "Powerful Indian boxing champion",
        "Graceful Chhau masked warrior",
        "Modern Indian classical musician",
        "Royal Bundelkhand warrior king",
        "-Finish-"
    ],

    "femaleSubjects": [
        "-None-",
        "Regal Rajputana queen in royal attire",
        "Ethereal South Indian classical dancer mid-performance",
        "Divine multi-armed goddess incarnation",
        "Modern Mumbai corporate queen",
        "Mystical Himalayan sadhvi in meditation",
        "Opulent Mughal begum with pearl jewelry",
        "Fierce Maratha warrior princess",
        "Traditional Kerala temple dancer",
        "Contemporary Delhi fashion influencer",
        "Rural Punjabi village beauty carrying brass pot",
        "Celestial apsara descending from heavens",
        "Radiant Kashmiri bride in traditional attire",
        "Powerful Bengali Durga warrior",
        "Elegant Tamil Brahmin beauty with jasmine flowers",
        "Graceful Odissi dancer in silver jewelry",
        "Sophisticated Bangalore tech CEO",
        "Ancient Chola empire empress",
        "Tribal Gond warrior queen with bow",
        "Royal Hyderabadi nawab begum",
        "Spiritual Ganga ghats yogini",
        "Modern Kolkata intellectual beauty",
        "Traditional Gujarati bride in heavy embroidery",
        "Fierce Naga tribal huntress",
        "Ethereal Konark temple dancer",
        "Luxurious Jaipur palace maharani",
        "Contemporary Chennai film star",
        "Ancient Vedic rishi’s daughter",
        "Powerful Rajasthani folk dancer",
        "Graceful Manipuri dancer in traditional costume",
        "Opulent Lucknowi courtesan beauty",
        "Modern Indian Air Force pilot officer",
        "Traditional Assamese Bihu dancer",
        "Royal Mysore palace princess",
        "Spiritual Varanasi ghats widow",
        "Fierce Sikh warrior princess",
        "Elegant Goan Catholic bride",
        "Contemporary Bollywood superstar",
        "Ancient Mauryan empire empress",
        "Tribal Santhal beauty with bow",
        "Royal Cochin princess in gold",
        "Mystical Rishikesh yoga guru",
        "Powerful Marathi lavani dancer",
        "Graceful Kathak royal courtesan",
        "Modern Indian Supreme Court judge",
        "Traditional Himachali mountain bride",
        "Ethereal Konkani beach beauty",
        "Opulent Awadhi begum with attar",
        "Fierce Northeast insurgent leader",
        "Spiritual Haridwar sadhvi in saffron",
        "Contemporary Indian Olympic athlete",
        "Ancient Indus Valley priestess",
        "Royal Mewar maharani with sword",
        "Graceful Mohiniyattam dancer",
        "Modern Indian astronaut",
        "Tribal Warli painter beauty",
        "Elegant Parsi nawar bride",
        "Powerful Rajput swordswoman",
        "Spiritual Ramlila performer as Sita",
        "Contemporary Indian classical vocalist",
        "-Finish-"
    ],

     "nsfwSubjects": [
        "-None-",
        "Obsidian-skinned succubus empress with glowing golden runes",
        "Living liquid-latex priestess fused with her habit",
        "Tentacle-corrupted temple devadasi with writhing halo",
        "Porcelain pleasure android leaking synthetic nectar",
        "Crimson-horned demoness mid-orgasmic inferno",
        "Mind-shattered seraphim with broken halo chains",
        "Bioluminescent fertility goddess with glowing womb sigils",
        "High-gloss rubber doll vacuum-sealed forever",
        "Corrupted valkyrie dripping black ichor",
        "Fleshcrafted broodmother swollen with offspring",
        "Oiled Amazonian war-goddess under arena floodlights",
        "Hypno-spiral courtesan with vacant glowing eyes",
        "Shibari-wrapped celestial seraph in glowing ropes",
        "Cum-glazed harem odalisque with pearl strands",
        "Living marionette controlled by golden orgasm strings",
        "Vampire maharani mid-bloodfeeding ecstasy",
        "Dragon-scale dominatrix exhaling smoke",
        "Alchemical fleshwarped beauty with extra lactating breasts",
        "Gimp-masked pet-play kitten with diamond collar",
        "Glass-encased living exhibition doll",
        "High-born succubus empress commanding submission",
        "Ethereal shibari muse suspended in silk",
        "Cyber-goth latex dominatrix with neon whip",
        "Imperial harem concubine dripping in gold",
        "Playful neko-maid with vibrating tail",
        "Exhibitionist netrunner with exposed ports",
        "Oil-slicked gladiatrix glistening",
        "Bondage fairy caught in golden webs",
        "Buxom dairy maid overflowing",
        "Exotic pole dancer wrapped in silk",
        "Wet-look siren emerging from milk",
        "Bedroom streamer mid-climax",
        "Rebellious sorority girl bound in ropes",
        "Lactating fertility idol with divine milk",
        "Living onahole android with vacuum seal",
        "Tentacle-filled shrine maiden",
        "Cum-inflated breeding vessel",
        "Shibari-wrapped royal concubine",
        "Latex-encased pleasure slave",
        "Demon-possessed dancer mid-exorcism orgasm",
        "-Finish-"
    ],
	
	"neutralSubjects": [
        "-None-",
        "Cyberpunk street samurai with glowing katana",
        "Futuristic chrome-skinned android",
        "Post-apocalyptic wasteland survivor in dust storm",
        "Alien emissary with bioluminescent skin patterns",
        "Time-displaced Victorian explorer",
        "Cloaked enigmatic assassin mid-leap",
        "Masked cyber-ninja perched on rooftop",
        "Ancient sentient war robot reactivated",
        "Ethereal ghost warrior in translucent armor",
        "Demonic entity with obsidian horns",
        "Celestial archangel with molten gold wings",
        "Elemental fire spirit manifesting in flames",
        "Void-born eldritch horror in human form",
        "Steampunk airship captain with mechanical arm",
        "Neon-lit corporate enforcer",
        "Intergalactic bounty hunter",
        "Quantum-phase assassin flickering in-out",
        "Biomechanical war construct",
        "Shadow-cloaked wraith assassin",
        "Holographic AI projection solidified",
        "Cryogenic awakened super-soldier",
        "Nano-swarm possessed human",
        "Reality-warping psychic operative",
        "Chrome desert nomad with sand goggles",
        "Arctic expedition survivor with frostbite scars",
        "Deep-sea pressurized exosuit diver",
        "Zero-gravity orbital mercenary",
        "Plague-doctor styled biohazard operative",
        "Ancient golem awakened in temple",
        "Living statue of marble warrior",
        "Mirror-dimensional doppelgänger",
        "Sandstorm-walking desert phantom",
        "Neon-drenched rooftop hacker",
        "Floating sky-island guardian",
        "Underground resistance leader",
        "Storm-riding thunder spirit",
        "Crystal-entity lifeform",
        "Volcanic lava-forged warrior",
        "Bioluminescent deep-ocean hybrid",
        "Quantum-entangled twin operative",
        "Antarctic research station survivor",
        "Mars colony red-dust rebel",
        "Venus acid-cloud sky pirate",
        "Titan methane-lake explorer",
        "Europa ice-drilling scientist-soldier",
        "Pluto dark-side miner",
        "Interstellar ark refugee commander",
        "Wormhole expedition vanguard",
        "Black-hole horizon observer",
        "Dyson-sphere construction overseer",
        "Ringworld horizon walker",
        "-Finish-"
    ],

    "femaleGenderList": [
        "Woman",
        "Girl",
        "Lady",
        "Female",
        "Matron",
        "Dame",
        "Gal",
        "Lass",
        "Miss",
        "Madam"
    ],

    "maleGenderList": [
        "Man",
        "Boy",
        "Gentleman",
        "Male",
        "Lad",
        "Guy",
        "Fellow",
        "Chap",
        "Mister",
        "Sir"
    ],

    "lookalikeList": [
        "-None-",
        "Jane Fonda",
        "Catherine Deneuve",
        "Brigitte Bardot",
        "Monica Bellucci",
        "Salma Hayek",
        "Nicole Kidman",
        "Angelina Jolie",
        "Charlize Theron",
        "Jennifer Connelly",
        "Scarlett Johansson",
        "Anne Hathaway",
        "Keira Knightley",
        "Emily Ratajkowski",
        "Jessica Chastain",
        "Jennifer Lopez",
        "Penélope Cruz",
        "Eva Green",
        "Ana de Armas",
        "Kristen Stewart",
        "Florence Pugh",
        "Anya Taylor-Joy",
        "Margot Robbie",
        "Gal Gadot",
        "Zendaya",
        "Deepika Padukone",
        "Priyanka Chopra",
        "Aishwarya Rai",
        "Timeless beauty of Monica Bellucci in her prime",
        "Audrey Hepburn elegant grace",
        "Marilyn Monroe 1950s bombshell glow",
        "Young Brigitte Bardot sun-kissed",
        "Natalie Portman Black Swan intensity",
        "Anya Taylor-Joy chess-queen features",
        "Margot Robbie Harley-Quinn playful madness",
        "Gal Gadot Wonder Woman strength",
        "Zendaya ethereal dune-princess",
        "Ana de Armas Bond-girl fire",
        "Sydney Sweeney modern bombshell",
        "Alexandra Daddario piercing eyes",
        "Madhubala","Waheeda Rehman", "Nutan","Meena Kumari","Nargis","Sadhana","Asha Parekh","Mumtaz","Zeenat Aman","Rekha","Hema Malini","Sridevi","Madhuri Dixit","Juhi Chawla","Kajol","Rani Mukerji","Preity Zinta","Aishwarya Rai","Priyanka Chopra","Deepika Padukone","Katrina Kaif","Anushka Sharma","Alia Bhatt","Shraddha Kapoor","Kiara Advani","Janhvi Kapoor","Sara Ali Khan","Tara Sutaria","Anya Taylor-Joy","Margot Robbie","Zendaya","Ana de Armas","Sydney Sweeney","Florence Pugh","Emma Watson","Natalie Portman","Scarlett Johansson","Gal Gadot","Alexandra Daddario","Emily Ratajkowski","Monica Bellucci (prime)","Salma Hayek (prime)","Penélope Cruz","Sofia Vergara","Eva Mendes","Jessica Alba","Megan Fox","Angelina Jolie (prime)","Kate Beckinsale","Charlize Theron","Nicole Kidman","Catherine Zeta-Jones","Jennifer Lopez","Beyoncé","Rihanna","Shakira","Adriana Lima","Gisele Bündchen","Marilyn Monroe (1950s)","Audrey Hepburn (1950s)","Elizabeth Taylor (1950s)","Sophia Loren (1950s)","Brigitte Bardot (1950s)","Grace Kelly","Jane Fonda (1960s)","Catherine Deneuve (1960s)","Raquel Welch (1960s)","Ursula Andress","Kim Novak","Natalie Wood","Faye Dunaway (1970s)","Jacqueline Bisset","Candice Bergen","Cindy Crawford (1990s)","Claudia Schiffer","Naomi Campbell","Kate Moss","Linda Evangelista",
        "-Finish-"
    ],

    "lookalikeListNSFW": [
        "Linda Lovelace",
        "Marilyn Chambers",
        "Georgina Spelvin",
        "Annette Haven",
        "Desireé Cousteau",
        "Seka",
        "Veronica Hart",
        "Lisa De Leeuw",
        "Kay Parker",
        "Samantha Fox",
        "Ginger Lynn",
        "Traci Lords",
        "Christy Canyon",
        "Nina Hartley",
        "Amber Lynn",
        "Porsche Lynn",
        "Hyapatia Lee",
        "Tracey Adams",
        "Barbara Dare",
        "Jeanna Fine",
        "Tori Welles",
        "Savannah",
        "Ashlyn Gere",
        "Deidre Holland",
        "Racquel Darrian",
        "Janine Lindemulder",
        "Asia Carrera",
        "Jenna Jameson",
        "Chasey Lain",
        "Kobe Tai",
        "Stephanie Swift",
        "Tera Patrick",
        "Briana Banks",
        "Nikita Denise",
        "Belladonna",
        "Stormy Daniels",
        "Jesse Jane",
        "Teagan Presley",
        "Sasha Grey",
        "Sunny Leone",
        "Bree Olson",
        "Alexis Texas",
        "Kayden Kross",
        "Stoya",
        "Asa Akira",
        "Riley Reid",
        "Skin Diamond",
        "Mia Khalifa",
        "Abella Danger",
        "Lana Rhoades","Emily Willis","Gianna Dior","Autumn Falls","Angela White","Violet Myers","Kendra Sunderland","Ella Knox","Skylar Vox","Gabriela Lopez","Valentina Nappi","Alina Lopez","Adriana Chechik","Kali Roses","Eva Elfie","Little Caprice","Tori Black","Mia Malkova","Jada Stevens","Lisa Ann","Nicolette Shea","Kagney Linn Karter","Madison Ivy","Brandi Love","Julia Ann","Phoenix Marie","Sara Jay","Romihi Nakamura","Hitomi Tanaka","Anri Okita","Yuma Asami","Maria Ozawa","Sora Aoi","Tia Ling","London Keyes","Asa Akira (early)","Katsuni","Aletta Ocean","Sophie Dee","Gianna Michaels","Carmel Moore","Shyla Stylez","Rachel Roxxx","Jayden Jaymes","Audrey Bitoni",  "-Finish-"
    ],

    "faceTypeList": [
        "-None-",
        "Oval face",
        "Round face",
        "Square face",
        "Heart-shaped face",
        "High cheekbones",
        "Chiseled jawline",
        "Soft features",
        "Sharp angular features",
        "Dimples",
        "Freckles",
        "Sharp North-Indian Aryan features",
        "Dravidian features with large expressive eyes",
        "Face adorned with a small round Bindi",
        "Face with heavy Kohl (Kajal) lined eyes",
        "Traditional ornate nose-ring (Nath) on face",
        "Face with Turmeric (Haldi) glow",
        "Perfect oval face with sharp features","Heart-shaped face with high cheekbones","Diamond face with dramatic jawline","Round youthful face with soft contours","Square face with strong bone structure","Long elegant face with refined features","Pear-shaped face with delicate chin","Oblong face with balanced proportions","Kashmiri almond eyes with fair complexion","Punjabi wheatish glow with sharp nose","Bengali large expressive eyes","South Indian dusky oval face","Gujarati soft round face with bindi","Marathi sharp Aryan features","Tamil classic Dravidian beauty face","Kerala long luscious hair framing face","Rajput royal sharp jawline","Sindhi fair heart-shaped face","Bihari traditional bindi-adorned face","Assamese delicate oriental features","Manipuri soft round innocent face","Goan mixed Portuguese-Indian features","Parsi refined aquiline nose","North Indian fair sharp features","South Indian dusky heart-shaped face","Himachali rosy mountain glow face","Naga tribal sharp cheekbones","Mizo soft East-Asian influenced face","Arunachali high-altitude sharp features","Sikkimese gentle Buddhist features","Jammu sharp Kashmiri features","Ladakhi Tibetan-influenced face","Konkan coastal sun-kissed face","Malabar classic Kerala features","Telugu sharp traditional features","Kannada soft oval face","Odia classic Eastern features","Tribal Gond sharp hunter face","Santhal tribal strong features","Bhil tribal proud sharp face","Warli artistic soft features","Irula forest sharp features","Toda pastoral soft face","Khasi matriarchal strong face","Garo gentle hill features","Jaintia elegant tribal face","Bodo warrior sharp features","Dimasa royal heritage face","Mishing riverine soft face","Rabha forest gentle features","Tiwa tribal strong jawline","Deori priestly refined face", "-Finish-"
    ],

    "femaleHairStyleList": [
        "-None-",
        "Waist-length silky straight hair",
        "Voluminous 90s supermodel blowout",
        "Cascading mermaid beach waves",
        "Messy bedhead long hair",
        "High sleek ponytail",
        "Short pixie cut",
        "Classic Bob cut",
        "Wet-look slicked back long hair",
        "Long thick black braid with tassel (Parandi)",
        "Traditional bun adorned with Jasmine flowers (Gajra)",
        "Loose hair with center-parting and Sindoor",
        "Oiled slicked-back bun",
        "Intricate bridal braided bun",
        "Long silky jet-black hair flowing freely","Thick waist-length traditional braid with parandi","Classic center-parted long hair with sindoor","Intricate South Indian jasmine-adorned bun","Royal Mughal layered hair with pearl strings","Loose waves with maang tikka framing face","Traditional Punjabi long oiled braid","Modern straight hair with golden highlights","Long black hair with Rajasthani borla","Sleek high ponytail with gajra","Voluminous 90s Bollywood blowout","Wet-look slicked back long hair","Messy beach waves with sea salt texture","Classic Bengali khopa bun with flowers","Elegant side-parted long curtain bangs","Floor-length traditional temple dancer hair","Oiled and tightly braided long hair","Royal crown braid with gold threads","Soft romantic curls with rose petals","Long straight hair with heavy kajal eyes","Traditional Kashmiri taranga headdress style","Loose hair with Kashmiri dejihor jewelry","Modern pixie cut with undercut","Short bob with blunt bangs","Long layered hair with feather extensions","Vintage victory rolls with vermilion","Traditional Himachali dhatu headscarf style","Long hair with Goan floral crown","Classic Parsi gara embroidery veil style","Long wavy hair with Mangalorean flowers","Traditional Assamese gamusa wrapped hair","Long silky hair with Naga bead ornaments","Modern mullet with colored streaks","Long hair with Rajput chooda bangles visible","Traditional Gujarati chanlo bun","Long hair with Marathi nath piercing","Classic Tamil mookuthi adorned hair","Long straight hair with Kerala mundu style","Traditional Odissi dancer’s tribhangi hair","Long hair with Rajasthani safas influence","Modern wolf cut layered hair","Long hair with Bihari tikuli forehead decor","Classic Punjabi phulkari dupatta hair","Long silky hair with Sindhi ajrak patterns","Traditional Rajput jadau hair jewelry","Long wavy hair with Konkani flowers","Classic Bengali shola crown style","Long hair with Manipuri potloi ornaments","Traditional Naga tribal bead hair","Long straight hair with Mizo puan wrap","Classic Arunachali tribal long braids","-Finish-"
		],

    "maleHairStyleList": [
        "-None-",
        "Short military buzz cut",
        "Slicked back pompadour",
        "Messy surfer waves",
        "Samurai top knot",
        "Viking braids with undercut",
        "Classic side part",
        "Bald with full beard",
        "Dreadlocks tied back",
        "Mullet",
        "Mohawk","Traditional Sikh turban with full beard","Long Rajput mustache with oiled hair","Classic South Indian mundu with short hair","Royal Mughal curled mustache and beard","Military buzz cut with handlebar mustache","Long sadhu matted jata hair","Clean-shaven modern corporate cut","Traditional Brahmin shikha tuft","Long Kashmiri taranga style hair","Short cropped army regulation cut","Classic Bollywood hero side-parted hair","Long Rajasthani pagdi turban style","Traditional Tamil vibhuti forehead hair","Long Parsi curled hair with cap","Military high-and-tight fade","Long Naga warrior topknot","Classic Punjabi folk singer long hair","Short neat IAS officer cut","Traditional Marathi pheta turban style","Long Goan Catholic slicked-back hair","Clean modern startup founder cut","Traditional Gujarati kediyu hair","Long Northeast tribal warrior hair","Short cricketer helmet-ready cut","Classic Bengali intellectual wavy hair","Military special forces shaved head","Long Sufi qawwal flowing hair","Traditional Rajput sword-master mustache","Short doctor professional cut","Long yogi topknot beard","Classic Bihari politician white kurta hair","Military parade perfect cut","Long Kashmiri pheran hair","Traditional Assamese gamusa turban style","Short police officer regulation cut","Long Naga spear warrior hair","Classic Bollywood villain slicked hair","Military commando buzz cut","Long sadhu saffron dreadlocks","Traditional Rajasthani royal mustache","Short modern metrosexual cut","Long tribal hunter braided hair","Classic South Indian temple priest hair","Military Gurkha regulation cut","Long Himalayan monk shaved head","Traditional Marwari turban style","Short cricketing legend cut","Long Sufi dervish spinning hair","Classic Punjabi bhangra dancer hair","Military paratrooper shaved sides",
        "-Finish-"
    ],

    "bodyTypeList": [
        "-None-",
        "athletic",
        "Herculean",
        "ripped",
        "toned",
        "curvy",
        "voluptuous",
        "hourglass",
        "busty",
        "Willowy frame",
        "slender",
        "petite",
        "tall",
        "average",
        "full-figured",
        "lithe dancer's build",
        "heavy powerlifter physique",
        "cybernetically enhanced body",
        "glowing ethereal form",
        "rugged battle-scarred frame",
        "soft renaissance curves",
        "Athletic toned physique with perfect proportions",
        "Herculean muscular build with vascular arms",
        "Ripped competition-ready bodybuilder physique",
        "Voluptuous hourglass figure with soft natural curves",
        "Curvy traditional Indian feminine silhouette with glowing skin",
        "Petite delicate frame with graceful long limbs",
        "Willowy supermodel height and elegant posture",
        "Busty natural feminine contours with golden glow",
        "Slender classical dancer’s lithe musculature",
        "Tall regal commanding presence with sharp collarbones",
        "Full-figured traditional Punjabi beauty with generous hips",
        "Lithe yoga practitioner with extreme flexibility",
        "Heavy powerlifter thick muscular thighs",
        "Statuesque Amazonian height and raw strength",
        "Chiseled Greek-god physique with marble-like definition",
        "Soft renaissance-painting curves with dusky South Indian tone",
        "Wheatish Haryanvi athletic build with strong shoulders",
        "Dusky Tamil graceful long-waisted proportions",
        "Fair Kashmiri delicate bone structure and swan neck",
        "Golden Rajasthani royal elegance with proud posture",
        "Soft Bengali feminine fullness with expressive collarbones",
        "Petite Northeast tribal agile mountain build",
        "Tall Sikh warrior athletic dominance",
        "Curvy Gujarati traditional bridal softness",
        "Slender Kerala classical dancer with perfect arches",
        "Muscular Maratha warrior broad-shouldered frame",
        "Voluptuous Hyderabadi nawabi opulent curves",
        "Athletic modern Mumbai fitness-model definition",
        "Hourglass Bihari traditional bride silhouette",
        "Petite Goan beach-body toned legs",
        "Strong Naga tribal hunter compact power",
        "Delicate Parsi refined elegant bone structure",
        "Ripped Delhi gym-warrior vascular forearms",
        "Soft Odia classical dancer graceful arms",
        "Muscular Rajput royal guard towering height",
        "Graceful Manipuri dancer extreme flexibility",
        "Full-figured Lucknowi royal softness and poise",
        "Athletic Bangalore tech-athlete lean muscle",
        "Curvy Awadhi traditional richness in hips",
        "Slender Konkani coastal sun-kissed frame",
        "Strong Jat farmer thick muscular neck",
        "Petite Sikkimese mountain leanness",
        "Tall Mewar royal commanding stature",
        "Soft Malayali coconut-oil glowing curves",
        "Muscular Gurkha soldier compact explosive power",
        "Curvy Marwari traditional opulent fullness",
        "Athletic Indian Olympic gymnast compact strength",
        "Strong Santhal tribal hunter raw endurance",
        "Graceful Parsi ballroom dancer elongated lines",
        "Ripped Bollywood action-hero shredded abs",
        "Soft Rajput royal feminine softness",
        "Muscular Northeast insurgent fighter wiry strength",
        "Full-figured Bengali intellectual beauty with soft arms",
        "Slender Ladakhi high-altitude endurance leanness",
        "Strong Mizo tribal warrior compact muscle",
        "Curvy Goan Portuguese-Indian blended curves",
        "Athletic Indian Air Force pilot functional muscle",
        "Petite Jain monk-like minimal body fat",
        "Tall Vijayanagara warrior king massive frame",
        "Soft Mauryan royal elegance with proud chest",
        "Muscular Pallava rock-cut temple guardian build",
        "Graceful Chola bronze-dancer perfect proportions",
        "Ripped modern Indian wrestler cauliflower ears strength",
        "Strong tribal Warli endurance runner legs",
        "Curvy Irula forest goddess natural shape",
        "Athletic Toda pastoral mountain strength",
        "Petite Khasi matriarchal graceful posture",
        "Strong Garo hill warrior explosive calves",
        "Full-figured Jaintia royal softness",
        "Slender Bodo riverine swimmer shoulders",
        "Muscular Dimasa royal guard broad back",
        "Graceful Mishing traditional dancer long neck",
        "Strong Tiwa tribal hunter raw power",
        "Soft Deori priestly refined posture",
        "Ripped Indian cricket fast-bowler shoulders",
        "Curvy traditional Rajasthani folk-dancer hips",
        "Athletic modern Indian supermodel long legs",
        "Strong Rajput swordmaster muscular forearms",
        "Petite modern Indian Instagram influencer waist",
        "Tall ancient Indus Valley noble stature",
        "Soft ancient South Indian queenly curves",
        "Muscular ancient North Indian king physique",
        "Graceful ancient apsara celestial proportions",
        "Full-figured ancient fertility goddess abundance",
        "Slender ancient mountain yogini leanness",
        "Curvy ancient desert nomad beauty",
        "Athletic ancient palace guard functional muscle",
        "Strong ancient tribal chief raw power",
        "Petite ancient spiritual seeker minimalism",
        "Ripped ancient war elephant rider strength",
        "Soft ancient royal bride gentle curves",
        "Muscular ancient lion-hunter shoulders",
        "Graceful ancient celestial dancer lines",
        "-Finish-"
    ],

    "nsfwBodyTypeList": [
		"-None-",
        "Shortstack: tiny height with massive curves",
        "Synthetic Perfection: porcelain finish",
        "Thicc: heavy lower body",
        "Spinner: petite flexible frame",
        "Amazonian Muscle Mommy",
        "Soft and Doughy: ultra-plush",
        "BBW: voluptuous frame",
        "Gothic-Chic: pale skin",
        "Milky Pale: translucent skin",
        "Oiled Hardbody: glistening muscles",
        "Sun-Kissed: bikini tan lines",
        "Rubber-Doll: synthetic skin texture",
        "Hyper-Busty: anime-style",
        "Pear-Goddess: massive hips",
        "Hairy Natural",
        "Sweaty and Grimy",
        "Latex-Clad",
        "Extreme hourglass 0.4 ratio",
        "Hyper-fertile breeding hips",
        "Transparent skin revealing glowing organs",
        "Body covered in living erotic tattoos",
        "Extra rows of heavy lactating breasts",
		"Extreme hourglass 0.45 waist-to-hip ratio with massive natural breasts",
        "Hyper-busty naturally lactating South Indian goddess physique",
        "Shortstack tiny frame with overflowing Punjabi curves",
        "Amazonian muscle goddess with wide breeding hips",
        "Soft ultra-plush doughy BBW traditional Indian fullness",
        "Pale gothic porcelain skin with translucent glowing veins",
        "Oiled glistening hardbody competition-ready abs and glutes",
        "Sun-kissed bikini tan lines with coconut-oil sheen",
        "Synthetic liquid-latex second skin vacuum-sealed shine",
        "Hyper-fertile wide Rajasthani breeding hips and tiny waist",
        "Transparent skin revealing glowing erotic chakra points",
        "Body covered in living glowing Sanskrit erotic tattoos",
        "Extra rows of heavy lactating breasts with gold piercings",
        "Tiny spinner flexible frame that folds completely",
        "Thicc lower-heavy thunder thighs and massive ass",
        "Pear-goddess massive hips with traditional henna",
        "Sweaty post-orgasm flush with real goosebumps and tremors",
        "Latex-clad permanent glossy second skin",
        "Cum-inflated swollen belly with visible movement",
        "Tentacle-filled glowing translucent womb",
        "Shibari rope-marked skin with diamond rope burns",
        "Wax-dripped red candle-play trails across breasts",
        "Pierced nipples with heavy traditional jhumka-style rings",
        "Collar-marked submissive neck with permanent bruise",
        "Bite-marked inner thighs dripping with saliva",
        "Whipped red welts across back and ass",
        "Bound wrist rope burns with silk restraints",
        "Gagged drooling mouth with traditional paan stains",
        "Blindfolded with silk saree fabric",
        "Leashed with diamond-studded gold collar",
        "Plugged tail with traditional peacock feathers",
        "Chastity belt in solid gold with filigree",
        "Inflated breast pump attached with real milk flowing",
        "Milking machine connected to swollen udders",
        "Oviposition egg-swollen belly glowing from within",
        "Demon-brand glowing Sanskrit marks on mons",
        "Angelic broken halo scar leaking golden ichor",
        "Succubus rune-covered skin pulsing red",
        "Vampire bite permanent marks on neck and breasts",
        "Werewolf claw scars across back in perfect symmetry",
        "Dragon-scale pattern lower body with tail",
        "Naga scale lower body merging into human torso",
        "Centaur powerful horse lower body with human curves",
        "Mermaid shimmering scale tail with wet-look skin",
        "Harpy winged arms with massive feathered wings",
        "Sphinx lion lower body with human goddess torso",
        "Minotaur massive horns and muscular bull legs",
        "Satyr furred goat legs with permanent erection",
        "Faun hoofed feet with flowering vines",
        "Dryad bark-textured skin with glowing sap",
        "Nymph translucent water-form body",
        "Siren hypnotic scale-covered breasts",
        "Banshee screaming mouth with ethereal glow",
        "Valkyrie golden armor marks burned into skin",
        "Geisha white makeup running from tears and sweat",
        "Maiko heavy makeup completely ruined",
        "Courtesan kohl-lined eyes smeared from ecstasy",
        "Odalisque henna-covered hands and feet",
        "Devadasi temple jewelry permanently fused to skin",
        "Apsara celestial gold jewelry embedded in flesh",
        "Yakshini treasure guardian with gem-encrusted nipples",
        "Kinnari bird-legged beauty with golden talons",
        "Nagakanya serpent lower body with human torso",
        "Rakshasi demonic beauty with extra mouths",
        "Dakini wrathful form with skull crown",
        "Yogini tantric pose frozen mid-orgasm",
        "Sadhvi ascetic markings glowing with sexual energy",
        "Rani royal bindu glowing between breasts",
        "Begum pearl-strung body dripping in milk",
        "Nawabzadi gold-dusted skin glistening with oil",
        "Maharani crown imprint burned into forehead",
        "Princess tiara shadow permanently marked",
        "Queen regal bearing with permanent submission collar",
        "Goddess divine aura with glowing yoni",
        "Devi supreme power leaking amrita",
        "Shakti primal energy with visible kundalini fire",
        "Kali fierce destruction with tongue out dripping",
        "Durga warrior strength with multiple bound arms",
        "Lakshmi abundant wealth with gold coins pouring from breasts",
        "Saraswati knowledge flow with veena strings as bondage",
        "Parvati devoted love with shiva lingam inside",
        "Sita loyal purity with permanent chastity glow",
        "Radha passionate devotion covered in gopi butter",
        "Rukmini royal grace with pearl cum strands",
        "Satyabhama fierce love with golden whip marks",
        "Draupadi unyielding strength with five husband brands",
        "-Finish-"
    ],

    "femaleBodyTypeList": [
        "-None-",
        "hourglass figure",
        "voluptuous",
        "curvy",
        "petite",
        "slender",
        "willowy",
        "athletic toned",
        "soft and chubby",
        "busty",
        "pear-shaped",
        "tall Amazonian",
        "lithe dancer's build",
        "fleshy renaissance build",
        "delicate fairy-like frame",
        "cybernetically enhanced female body",
        "pregnant",
        "wide hips",
        "flat chested",
        "gymnast build",
        "-Finish-"
    ],

    "maleBodyTypeList": [
        "-None-",
        "V-taper bodybuilder physique",
        "lean swimmer's build",
        "massive strongman bulk",
        "rugged lumberjack frame",
        "wirey martial artist build",
        "broad soldier shoulders",
        "beer belly dad bod",
        "towering giant stature",
        "ripped 8-pack abs",
        "-Finish-"
    ],

    "pelvisList": [
        "-None-",
        "wide hips",
        "narrow hips",
        "curvy hips",
        "hourglass hips",
        "slender hips",
        "child-bearing hips",
        "hip dips",
        "flared hips",
        "rounded hips",
        "prominent hip bones",
        "anterior pelvic tilt",
        "violin hips",
        "full hips",
        "generous hips",
        "bubble butt",
        "heart-shaped buttocks",
        "perky buttocks",
        "flat buttocks",
        "heavy lower body distribution",
        "wide hips and small waist",
        "thigh gap",
        "prominent buttocks",
        "muffin top",
        "-Finish-"
    ],

    "femalePelvisList": [
        "-None-",
        "wide hips",
        "narrow hips",
        "curvy hips",
        "hourglass hips",
        "slender hips",
        "child-bearing hips",
        "hip dips",
        "flared hips",
        "rounded hips",
        "prominent hip bones",
        "anterior pelvic tilt",
        "violin hips",
        "full hips",
        "generous hips",
        "bubble butt",
        "heart-shaped buttocks",
        "perky buttocks",
        "flat buttocks",
        "small buttocks",
        "heavy lower body distribution",
        "wide hips and small waist",
        "thigh gap",
        "prominent buttocks",
        "muffin top",
        "-Finish-"
    ],

    "malePelvisList": [
        "-None-",
        "Narrow athletic hips",
        "Muscular glutes",
        "Strong quadriceps definition",
        "V-cut abs leading downwards",
        "Bulky powerlifter legs",
        "Lean runner's legs",
        "Solid trunk",
        "Square hips",
        "Defined adonis belt",
        "Heavy muscular thighs",
        "Tight glutes",
        "Flat buttocks",
        "Strong lower back",
        "-Finish-"
    ],

    "eyeColorList": [
        "-None-",
        "Blue eyes",
        "Green eyes",
        "Brown eyes",
        "Hazel eyes",
        "Grey eyes",
        "Amber eyes",
        "Violet eyes",
        "Black eyes",
        "Ice blue eyes",
        "Emerald green eyes",
        "Golden eyes",
        "Red eyes (albino)",
        "Glowing blue eyes",
        "Glowing red eyes",
        "Heterochromia",
        "Blind white eyes",
        "Cybernetic eyes",
        "Reptilian slit pupils",
        "-Finish-"
    ],

    "breastTypeList": [
        "-None-",
        "delicate rosebud breasts",
        "graceful teardrop curves",
        "full, perfectly rounded breasts",
        "petite, pert breasts",
        "elegant C-cup swells",
        "soft, natural handfuls",
        "slender aristocratic chest",
        "generous yet weightless breasts",
        "small, high-set breasts",
        "pale moonlit cleavage",
        "warm sun-kissed curves",
        "modest A-cup treasures",
        "supple, youthful breasts",
        "soft hourglass swells",
        "delicate porcelain décolletage",
        "full, maternal curves",
        "gentle, athletic breasts",
        "lush, natural D-cup curves",
        "ethereal, almost weightless breasts",
        "-Finish-"
    ],

    "nsfwBreastList": [
        "Enormous, perfectly round breasts glistening with baby oil",
        "Heavy, pendulous breasts hanging free",
        "Breasts squeezed together by tight latex",
        "Nipples pierced with thick silver barbells",
        "Massive, gravity-defying breasts",
        "Pale, milky breasts covered in wax",
        "Breasts bound in intricate red shibari rope",
        "Huge lactating breasts spraying milk",
        "Nipples clamped with weighted clover clamps",
        "Breasts wrapped in transparent latex",
        "Perfect teardrop breasts with puffy areolas",
        "Breasts covered in thick ropes of semen",
        "Dark, swollen areolas",
        "Breasts pressed hard against glass",
        "Nipples pierced with glowing neon rings",
        "Underboob heavily shadowed",
        "Breasts encased in clear resin",
        "Huge, soft breasts with stretch marks",
        "Nipples leaking thick honey",
        "Breasts in a cupless latex bra"
    ],

    "nippleTypeList": [
        "-None-",
        "Soft Pink",
        "Dark Brown",
        "Pale",
        "Dusky",
        "Large Areola",
        "Small Areola",
        "Puffy",
        "Inverted",
        "Pierced (Silver Barbell)",
        "Pierced (Gold Ring)",
        "Heart-shaped Pasties",
        "Star-shaped Pasties",
        "-Finish-"
    ],

    "nippleShapeList": [
        "-None-",
        "Round",
        "Oval",
        "Protruding",
        "Flat",
        "Cone shaped",
        "-Finish-"
    ],

    "vaginaTypeList": [
        "-None-",
        "Clean Shaven",
        "Trimmed Landing Strip",
        "Thick Natural Bush",
        "Neat Triangle Trim",
        "Heart-shaped Trim",
        "Light Stubble",
        "Hairy",
        "Cameltoe (visible through clothing)",
        "-Finish-"
    ],

    "vaginaShapeList": [
        "-None-",
        "Plump",
        "Petite",
        "Innie",
        "Outie",
        "Prominent",
        "Tight",
        "Gaping",
        "-Finish-"
    ],

    "maleUpperBody": [
        "-None-",
        "t-shirt",
        "wet t-shirt",
        "tank top",
        "hoodie",
        "turtleneck sweater",
        "flannel shirt",
        "button-down shirt",
        "leather jacket",
        "denim jacket",
        "bomber jacket",
        "trench coat",
        "suit jacket",
        "vest",
        "poncho",
        "fur coat",
        "windbreaker",
        "mesh top",
        "bondage harness (chest)",
        "latex corset",
        "choker",
        "-Finish-"
    ],

    "femaleUpperBody": [
        "-None-",
        "t-shirt",
        "tank top",
        "hoodie",
        "leather jacket",
        "denim jacket",
        "silk blouse",
        "crop top",
        "corset",
        "blazer",
        "sports bra",
        "Embroidered Saree Blouse (Choli)",
        "Silk Anarkali Kurta",
        "Sheer Dupatta wrapped around chest",
        "Cotton Chikankari Kurti",
        "tube top",
        "off-shoulder top",
        "halter top",
        "bustier",
        "camisole",
        "sci-fi armor (chest)",
        "fantasy armor (chest)",
        "knight's breastplate",
        "chainmail",
        "mage robes",
        "lab coat",
        "space suit (torso)",
        "bikini top",
        "lingerie top",
        "bra",
        "kimono (upper)",
        "peasant top",
        "poncho",
        "fur coat",
        "windbreaker",
        "bodysuit",
        "lace bra",
        "push-up bra",
        "plunging neckline top",
        "strappy top",
        "leather corset",
        "satin camisole",
        "underboob crop top",
        "harness",
        "cut-out top",
        "silk robe (open)",
        "strappy bra",
        "choker",
        "shawl",
        "-Finish-"
    ],

    "femaleUpperBodyNSFW": [
        "nipple pasties",
        "open-cup bra",
        "cupless bra",
        "bondage top",
        "bondage harness",
        "sheer robe",
        "latex corset",
        "vinyl bustier",
        "chain top",
        "leash collar",
        "fishnet body stocking",
        "wetlook top",
        "low-cut top",
        "underbust corset",
        "sheer turtleneck",
        "strapless bra",
        "transparent shirt",
        "string bikini",
        "see-through hoodie",
        "sheer blouse",
        "deep cleavage",
        "latex top",
        "fishnet top",
        "micro bikini",
        "sheer bra",
        "vinyl top",
        "mesh top",
        "nothing but a thin silver body chain",
        "completely topless with diamond pasties",
        "micro latex bralette",
        "transparent mesh crop top",
        "open-cup leather harness",
        "sheer black lace bodysuit",
        "wet white t-shirt clinging transparently",
        "body painted with liquid latex",
        "open-front latex bolero jacket",
        "bandage wrap top slipping",
        "glossy black tape X pasties",
        "metallic chainmail bikini top"
    ],

    "maleLowerBody": [
        "-None-",
        "jeans",
        "ripped jeans",
        "skinny jeans",
        "baggy jeans",
        "sweatpants",
        "leather pants",
        "denim shorts",
        "cargo shorts",
        "business slacks",
        "cargo pants",
        "chaps",
        "briefs",
        "boxers",
        "kilt",
        "bondage pants",
        "vinyl pants",
        "latex pants",
        "-Finish-"
    ],

    "femaleLowerBody": [
        "-None-",
        "jeans",
        "leggings",
        "leather pants",
        "denim shorts",
        "miniskirt",
        "pleated skirt",
        "pencil skirt",
        "yoga pants",
        "Flowing Silk Saree drape",
        "Voluminous Lehenga Skirt",
        "Patiala Salwar pants",
        "Tight Churidar pants",
        "Sharara pants",
        "ripped jeans",
        "skinny jeans",
        "baggy jeans",
        "sweatpants",
        "daisy dukes",
        "plaid skirt",
        "long skirt",
        "A-line skirt",
        "ballroom skirt",
        "cargo pants",
        "chaps",
        "sci-fi armor (legs)",
        "bikini bottom",
        "lingerie bottom",
        "panties",
        "boy shorts",
        "tutu",
        "fishnet stockings",
        "garter belt",
        "micro skirt",
        "leather miniskirt",
        "vinyl miniskirt",
        "lace panties",
        "high-slit skirt",
        "latex skirt",
        "latex leggings",
        "unzipped jeans",
        "satin panties",
        "leg warmers",
        "ankle socks",
        "-Finish-"
    ],

    "femaleLowerBodyNSFW": [
        "thong",
        "g-string",
        "sheer panties",
        "see-through skirt",
        "cheeky shorts",
        "booty shorts",
        "bondage pants",
        "micro bikini bottom",
        "see-through pants",
        "open-front skirt",
        "vinyl pants",
        "wet leggings",
        "low-rise jeans",
        "crotchless panties",
        "strappy panties",
        "lace thong",
        "vinyl panties",
        "latex panties",
        "string bikini bottom",
        "garter belt",
        "thigh-highs",
        "sheer stockings",
        "fishnet stockings",
        "harness",
        "see-through leggings",
        "wetlook leggings",
        "super short shorts",
        "open-back panties",
        "side-slit skirt",
        "chaps (no pants)"
    ],

    "maleFootwearList": [
        "-None-",
        "sneakers",
        "running shoes",
        "dress shoes",
        "oxfords",
        "boots",
        "work boots",
        "combat boots",
        "sandals",
        "flip-flops",
        "barefoot",
        "-Finish-"
    ],

    "femaleFootwearList": [
        "-None-",
        "heels",
        "sneakers",
        "boots",
        "combat boots",
        "sandals",
        "barefoot",
        "Embroidered Juttis",
        "Kolhapuri Chappals",
        "Golden Mojaris",
        "Payal (Anklets) on bare feet",
        "stiletto heels",
        "block heels",
        "kitten heels",
        "platform heels",
        "pumps",
        "Glass slippers",
        "ballet flats",
        "gladiator sandals",
        "wedges",
        "ankle boots",
        "knee-high boots",
        "thigh-high boots",
        "strappy heels",
        "clear heels",
        "fishnet heels",
        "platform sneakers",
        "fur boots",
        "moon boots",
        "strappy sandals",
        "gogo boots",
        "Doc Martens",
        "roller skates",
        "satin heels",
        "patent leather heels",
        "socks and heels",
        "Converse",
        "-Finish-"
    ],

    "headJewelleryList": [
        "-None-",
        "Diamond Tiara",
        "Bohemian Flower Crown",
        "Silk Turban Headband",
        "Gothic Black Lace Veil",
        "Gold Maang Tikka (Indian)",
        "Heavy Bridal Matha Patti",
        "Pearl-encrusted Hair Clips",
        "Butterfly Hairpins",
        "Jeweled Fascinator Hat",
        "Cyberpunk LED Headset",
        "Velvet Ribbon Bow",
        "Gajra (Jasmine flowers)",
        "-Finish-"
    ],

    "earJewelleryList": [
        "-None-",
        "Solitaire Diamond Studs",
        "Oversized Gold Hoops",
        "Elegant Pearl Drop Earrings",
        "Heavy Gold Jhumkas (Indian)",
        "Kundan Chandbalis",
        "Edgy Ear Cuffs",
        "Long Tassel Earrings",
        "Geometric Art Deco Earrings",
        "Feather Bohemian Earrings",
        "Crystal Chandelier Earrings",
        "Punk Safety Pin Earrings",
        "Multiple Piercing Set",
        "-Finish-"
    ],

    "neckJewelleryList": [
        "-None-",
        "Minimalist Gold Chain",
        "Single Pearl Pendant",
        "Diamond Tennis Necklace",
        "Gothic Velvet Choker",
        "Mangalsutra (Indian)",
        "Heavy Kundan Bridal Choker",
        "Statement Bib Necklace",
        "Infinity Scarf (Jeweled)",
        "Platinum Cross Pendant",
        "Cyber-Goth Spiked Choker",
        "Multi-layered Rani Haar",
        "-Finish-"
    ],

    "armJewelleryList": [
        "-None-",
        "Sleek Smart Watch",
        "Distressed Leather Wristband",
        "Cartier-style Gold Bangle",
        "Bajuband (Indian Armlet)",
        "Red Bridal Chooda",
        "Diamond Tennis Bracelet",
        "Bohemian Stacked Beaded Bracelets",
        "Upper Arm Cuff (Spiral)",
        "Viking Torc Armlet",
        "Stack of Colorful Glass Bangles",
        "-Finish-"
    ],

    "handJewelleryList": [
        "-None-",
        "Classic Diamond Wedding Ring",
        "Black Leather Gloves",
        "Gold Signet Ring",
        "Haath Phool (Indian Hand Flower)",
        "Lace Gothic Gloves",
        "Bohemian Midi Rings",
        "Satin Opera Gloves",
        "Chunky Gemstone Cocktail Ring",
        "Mehndi (Henna) patterns",
        "Fingerless Biker Gloves",
        "Claw Rings",
        "-Finish-"
    ],

    "activityList": [
        "-None-",
        "gazing intensely into camera with smoldering eyes",
        "breathing deeply with chest rising dramatically",
        "tilting head slightly while biting lower lip",
        "running fingers slowly through flowing hair",
        "parting lips in subtle gasp of pleasure",
        "arching back with graceful fluid motion",
        "tracing fingertips lightly along collarbone",
        "closing eyes in complete serene surrender",
        "smiling with mysterious knowing expression",
        "whispering ancient mantra with moving lips",
        "inhaling deeply as if drawing in cosmic energy",
        "releasing slow controlled breath with visible relief",
        "turning head slowly to reveal perfect profile",
        "blinking slowly with heavy bedroom eyes",
        "licking lips with deliberate sensual motion",
        "drawing invisible patterns on own thigh",
        "stretching arms overhead with cat-like grace",
        "shifting weight from one hip to another",
        "rolling shoulders back with confident poise",
        "tucking hair behind ear with elegant fingers",
        "caressing own neck with feather-light touch",
        "fluttering eyelashes in playful seduction",
        "pursing lips as if about to speak secret",
        "exhaling warm breath visible in cool air",
        "tilting chin upward in royal defiance",
        "lowering gaze demurely then looking up through lashes",
        "smirking with one corner of mouth lifted",
        "drawing slow circle on own sternum",
        "flexing toes in silent anticipation",
        "parting knees slightly then pressing together",
        "trailing fingers down own forearm",
        "inhaling scent from wrist with closed eyes",
        "releasing soft barely audible moan",
        "tensing then relaxing abdominal muscles",
        "rotating wrists in slow graceful circles",
        "tapping fingers rhythmically on thigh",
        "swaying hips in barely perceptible rhythm",
        "contracting then releasing pelvic floor",
        "blushing visibly from chest to cheeks",
        "shivering with visible goosebumps rising",
        "trembling slightly with building anticipation",
        "whimpering softly with parted lips",
        "gasping sharply as if touched unexpectedly",
        "moaning low and throaty from deep within",
        "crying out in sudden overwhelming ecstasy",
        "screaming in raw primal release",
        "laughing with pure abandoned joy",
        "sobbing with intense emotional overflow",
        "whispering sacred syllables under breath",
        "-Finish-"
    ],

    "femaleActivityList": [
        "-None-",
        "Striking a high-fashion vogue pose",
        "Sitting elegantly with crossed legs",
        "Executing a graceful ballet arabesque",
        "Curtsying deeply",
        "Spinning wildly in a flowing dress",
        "Blowing a kiss",
        "Adjusting a garter",
        "Arching back sensually",
        "Walking with a confident strut",
        "Applying lipstick",
        "Dancing a tribal bellydance",
        "Lounging like a pin-up model",
        "Holding a wine glass",
        "Praying with hands clasped",
        "Floating effortlessly",
        "Casting a spell",
        "Looking over shoulder",
        "Sipping tea in a garden",
        "Reading a grimoire",
        "Stretching arms overhead",
        "-Finish-"
    ],

    "maleActivityList": [
        "-None-",
        "Standing in a commanding general's power stance",
        "Drawing a broadsword",
        "Adjusting a tie",
        "Flexing biceps",
        "Smoking a cigar",
        "Sitting manspread on a throne",
        "Sharpening an axe",
        "Performing a haka war dance",
        "Saluting",
        "Crossing arms defiantly",
        "Resting a heavy weapon on shoulder",
        "Walking away from an explosion",
        "Drinking a tankard of ale",
        "Checking a pocket watch",
        "Clenching fists",
        "Leaning coolly against a car",
        "Sprinting into battle",
        "Meditating",
        "Hacking a terminal",
        "Looking at the horizon",
        "-Finish-"
    ],

    "nsfwActivityList": [
        "Being double-penetrated by massive demonic cocks",
        "Covered head-to-toe in thick layers of bukkake",
        "Suspended in complex glowing shibari",
        "Deepthroating a tentacle that pulses",
        "Riding a sybian until eyes roll back",
        "Fucked missionary bound in chains",
        "Milked by mechanical pumps",
        "Gangbanged by shadow clones",
        "Choking on cum upside-down",
        "Anally stretched by knotted cock",
        "Fisted to the elbow",
        "Used as a urinal",
        "Oviposition: eggs being pushed deep",
        "Titfucked between lactating breasts",
        "Edged for hours",
        "Facefucked until mascara runs",
        "Covered in wax while fucked",
        "Forced orgasm denial",
        "Inflated with cum",
        "Double anal",
        "Creampied consecutively",
        "Electro-stimulated",
        "Fucked by machine",
        "Bound in latex vacuum bed",
        "Used as living fleshlight",
        "Tentacle gangbang",
        "Public use gloryhole",
        "Kneeling in absolute devotion",
        "Struggling against tentacles",
        "Bent over a desk",
        "Displayed in glass cylinder",
        "Spreading legs wide",
        "Slowly pulling down panties",
        "Locked in a pillory",
        "Riding mechanical bull",
        "Pressed against wet glass",
        "Crawling seductively",
        "Holding a riding crop",
        "Gagged with silk",
        "Deep-throating a lollipop"
    ],

    "femaleExpressionList": [
        "-None-",
        "A mysterious Mona Lisa smile",
        "Eyes sparkling with tears",
        "A playful wink",
        "Biting lip in anticipation",
        "Radiating maternal warmth",
        "A seductive heavy-lidded gaze",
        "Pouting playfully",
        "Wide-eyed innocence",
        "A serene calm",
        "Giggling with joy",
        "Terrified vulnerability",
        "Blushing deeply",
        "A cold haughty sneer",
        "Lost in daydreaming",
        "Fierce glare",
        "Softly singing",
        "Divine revelation",
        "Crying softly",
        "Dazzling smile",
        "Whispering",
        "intense smoldering bedroom eyes",
        "soft vulnerable gaze with parted lips",
        "mysterious half-smile with knowing eyes",
        "complete serene bliss with closed eyes",
        "playful mischievous grin with tongue tip",
        "devastatingly sultry heavy-lidded stare",
        "innocent wide-eyed wonder with slight smile",
        "regal imperious gaze down nose",
        "tender loving warmth radiating from eyes",
        "ferocious passionate intensity burning",
        "shy demure downward gaze with blush",
        "wicked predatory smile with visible teeth",
        "peaceful meditation with gentle smile",
        "ecstatic open-mouthed surrender",
        "defiant challenging stare with raised chin",
        "melting adoration with soft eyes",
        "coy sideways glance with bitten lip",
        "divine compassion with gentle smile",
        "raw animal lust with dilated pupils",
        "heartbroken vulnerability with wet eyes",
        "joyful laughter with crinkled eyes",
        "seductive invitation with crooked finger",
        "spiritual transcendence with upward gaze",
        "dominant commanding presence in eyes",
        "submissive surrender with lowered eyes",
        "curious fascination with tilted head",
        "orgasmic release with rolled-back eyes",
        "teasing playful wink with tongue out",
        "devotional reverence with folded hands",
        "feral wild intensity with bared teeth",
        "-Finish-"
    ],

    "maleExpressionList": [
        "-None-",
        "Rugged stare",
        "Charismatic smirk",
        "Gritting teeth in rage",
        "Cold calculating gaze",
        "Winking playfully",
        "Thousand-yard stare",
        "Stoic mask",
        "Roaring with laughter",
        "Focused squint",
        "Sneering",
        "Grimace of pain",
        "Kingly authority",
        "Jaw set in determination",
        "Skeptical eyebrow raise",
        "Feral grin",
        "Shouting commands",
        "Fatherly pride",
        "Eyes burning with magic",
        "Melancholic brooding",
        "Spitting blood",
        "-Finish-"
    ],

    "nsfwExpressionList": [
        "Classic ahegao: eyes rolled back, tongue lolling",
        "Mind-broken vacant stare",
        "Cross-eyed orgasm with tears",
        "Screaming in silent ecstasy",
        "Begging with puppy-dog eyes",
        "Post-orgasm blank face with drool",
        "Hypnotized spiral eyes",
        "Biting lip hard enough to draw blood",
        "Eyes squeezed shut in pleasure",
        "Feral snarl of dominance",
        "Glazed-over submission",
        "Face frozen mid-squirt",
        "Mascara running from tears",
        "Delirious smile",
        "Vacant doll eyes with hearts",
        "Pleading 'more'",
        "Afterglow glow",
        "Biting pillow to muffle screams",
        "Tongue trying to catch cum"
    ],

    "backgrounds": [
        "-None-",
        "majestic marble palace hall with 50-foot gold-inlaid ceilings",
        "moonlit enchanted forest clearing",
        "grand rococo ballroom lit by floating chandeliers",
        "sunrise atop a mist-shrouded mountain temple",
        "opulent Ottoman throne room",
        "twilight rose garden labyrinth",
        "ancient elven tree-palace",
        "golden autumn cathedral of stained glass",
        "baroque Venetian masquerade balcony",
        "snowbound ice palace with aurora borealis",
        "lavish Persian harem with silk cushions",
        "cherry-blossom shrine atop a cliff",
        "gothic cathedral interior with incense",
        "sun-drenched Mediterranean courtyard",
        "floating sky palace of white marble",
        "secret moonlit lagoon with bioluminescence",
        "imperial Chinese palace garden",
        "victorian greenhouse with exotic orchids",
        "ancient Greek temple at sunset",
        "grand library with floating candlelight",
        "crystal cavern palace",
        "misty bamboo grove",
        "lavish art-nouveau boudoir",
        "starlit desert oasis palace",
        "frost-covered winter rose conservatory",
        "A sprawling cyberpunk metropolis drenched in neon rain",
        "An abandoned space station",
        "A pristine high-tech laboratory",
        "A colossal Mars colony biodome",
        "A fortified underground bunker",
        "The bridge of an alien starship",
        "A post-apocalyptic wasteland",
        "Ancient stone ruins with glowing moss",
        "A subterranean crystal cavern",
        "A dragon's lair with gold",
        "A steampunk clockwork city",
        "A misty redwood forest",
        "A volcanic landscape",
        "A tropical waterfall lagoon",
        "Endless shifting desert dunes",
        "Frozen arctic tundra",
        "A storm-tossed ocean",
        "A gritty noir alleyway",
        "A luxurious penthouse",
        "A bustling Tokyo street market",
        "A haunted Gothic mansion",
        "A grime-covered factory",
        "A peaceful Zen garden",
        "A wizard's tower study",
        "A medieval battlefield",
        "A dimly lit master bedroom",
        "A steamy glass shower",
        "A neon-lit nightclub",
        "A bubbling jacuzzi in snow",
        "A love hotel room with mirrors",
        "A private infinity pool",
        "A photography studio with white background",
        "Opulent 18th-century Jaipur City Palace courtyard at golden hour",
        "Misty Varanasi ghats with thousands of glowing diyas on Ganga",
        "Ancient sun-lit Khajuraho temple carvings with soft bokeh",
        "Majestic snow-capped Himalayan peaks behind Kedarnath temple",
        "Royal durbar hall of Mysore Palace with crystal chandeliers",
        "Golden desert dunes of Jaisalmer under dramatic sunset sky",
        "Lush green Kerala backwaters with traditional houseboat",
        "Massive marble interiors of Taj Mahal at dawn",
        "Ancient stone steps of Hampi Virupaksha temple",
        "Neon-drenched Mumbai Marine Drive at night with wet reflections",
        "Rooftop view of Kolkata Victorian architecture during monsoon",
        "Ancient Ellora cave temple lit by dramatic shafts of light",
        "Rajasthani haveli courtyard with intricate blue pottery",
        "Kashmiri shikara on serene Dal Lake with autumn chinar trees",
        "Golden Amritsar Harmandir Sahib reflecting in sarovar",
        "Ancient Chola bronze-lit Brihadeeswara temple interior",
        "Goa Portuguese-era church ruins with overgrown bougainvillea",
        "Ladakh monastery perched on dramatic mountain cliff",
        "Rural Punjab golden wheat fields at sunset",
        "Mehrangarh Fort towering over blue city of Jodhpur",
        "Ancient stepwell Chand Baori with perfect geometric shadows",
        "Hyderabad Charminar surrounded by bustling old city",
        "Konark Sun Temple wheel carved wall with dramatic side light",
        "Udaipur Lake Palace floating on Pichola Lake at twilight",
        "Ancient Nalanda University ruins with soft morning mist",
        "Serenity of Rishikesh Ganga aarti with hundreds of flames",
        "Majestic Victoria Memorial Kolkata surrounded by gardens",
        "Ancient Ajanta cave murals lit by soft natural light",
        "Royal Amber Fort elephant courtyard with dramatic sky",
        "Munnar tea plantations with rolling green hills and mist",
        "Ancient Mahabalipuram shore temple with crashing waves",
        "Palace of Winds Hawa Mahal Jaipur with perfect symmetry",
        "Sacred Pushkar Lake surrounded by 52 ghats",
        "Dramatic Qutub Minar against stormy monsoon sky",
        "Ancient Badami cave temples with red sandstone glow",
        "Golden Temple reflecting in water during blue hour",
        "Fatehpur Sikri deserted red sandstone city at sunset",
        "Ranthambore Fort ruins with jungle overgrowth",
        "Ancient Tanjore palace courtyard with Nandi statue",
        "Varanasi narrow lanes with colorful walls and sadhus",
        "Jaisalmer Fort living city glowing at night",
        "Ancient Pattadakal temple complex with perfect symmetry",
        "Leh Palace overlooking Indus valley at golden hour",
        "Ancient Belur temple intricate stone carvings",
        "Somnath temple facing Arabian Sea at dramatic sunset",
        "Ancient Halebidu temple with Hoysala architecture details",
        "Kochi Chinese fishing nets at sunset with warm tones",
        "Ancient Warangal Fort thousand pillar temple",
        "Dramatic Chittorgarh Fort victory tower at sunrise",
        "Ancient Gwalior Fort with blue tile work",
		 "-Finish-"
    ],

	"styleList": [
		"-None-",
		"Celestial Baroque",
		"Cybernetic Renaissance",
		"Eldritch Art Nouveau",
		"Bioluminescent Solarpunk",
		"Grimdark Gothic Sci-Fi",
		"Translucent Crystalism",
		"Liquid Gold Kintsugi",
		"Neon-Noir Impressionism",
		"Unreal Engine 5.4 Nanite Render",
		"Weta Digital VFX Style",
		"Riot Games Splash Art",
		"Studio Ghibli x Cyberpunk",
		"Dark Souls Concept Art",
		"Alex Ross Realism",
		"H.R. Giger Biomechanical",
		"Makoto Shinkai Cloudscape",
		"Iridescent Holography",
		"Obsidian and Marble",
		"Vaporwave Glitch Art",
		"Etched Copperplate",
		"Double Exposure Silhouette",
		"Alphonse Mucha x Cyberpunk 2077",
		"Greg Rutkowski Epic Fantasy",
		"Beeple Everyday Realism",
		"Loish Dreamy Portraiture",
		"Ross Tran Romantic Luminism",
		"Sakimichan Anime Realism",
		"WLOP Ghostblade Ethereal",
		"Akihiko Yoshida Final Fantasy Tactics",
		"Tetsuya Nomura Kingdom Hearts",
		"Shigenori Soejima Persona Aesthetic",
		"Zdzisław Beksiński Nightmare Surrealism",
		"Simon Stålenhag Retro-Futurism",
		"James Jean Fables Cover Art",
		"Krenz Cushart Hyper-Detail",
		"Ilya Kuvshinov Minimal Anime",
		"Artgerm Ultra-Smooth Comic",
		"Guweiz Urban Street Fashion",
		"Ruan Jia Cinematic Fantasy",
		"Feng Zhu Concept Design",
		"Sparth Sci-Fi Environment",
		"Moebius Desert Punk",
		"Syd Mead Blade Runner Future",
		"Shinkawa Metal Gear Ink",
		"Katsuya Terada Erotica Grotesque",
		"Range Murata Robot Girls",
		"Hyung-tae Kim Magna Carta",
		"Amano Final Fantasy Watercolor",
		"Beksinski x Giger Hybrid",
		"Studio SHAFT Head-Tilt Aesthetic",
		"Kyoto Animation Soft Glow",
		"-Finish-"
	],

	"effectList": [
		"-None-",
		"Zero-Gravity Suspension",
		"Quantum Disintegration",
		"Floral Overgrowth",
		"Chromatic Aberration",
		"Diamond Dust",
		"Molten Gold Dripping",
		"Energy Aura",
		"Nebula Infusion",
		"Shattered Glass Reality",
		"Motion Blur Speed Lines",
		"Burning Embers",
		"Data Stream Matrix",
		"Spectral Ghosting",
		"Ink in Water",
		"Prismatic Light Refraction",
		"Crystal Fracturing",
		"Liquid Mercury Flow",
		"Holographic Glitch",
		"Ethereal Particle Dissolve",
		"Cosmic Starfield Birth",
		"Vaporwave Grid Collapse",
		"Frozen Time Shatter",
		"Bioluminescent Veins",
		"Aurora Borealis Skin",
		"Phoenix Flame Rebirth",
		"Smoke and Mirror Duplicates",
		"Glitch Chroma Separation",
		"Floating Sakura Petals",
		"Void Black Hole Pull",
		"Golden Hour Lens Flares",
		"Rainbow Oil Slick Surface",
		"Neon Circuit Traces",
		"Cinematic Anamorphic Streaks",
		"Iridescent Feather Decay",
		"Lightning Energy Discharge",
		"Butterfly Wing Powder Burst",
		"Digital Rain Corruption",
		"Marble Statue Cracking",
		"Soft Pastel Smoke Swirl",
		"Starlight Sparkle Cascade",
		"Retro VHS Tracking Lines",
		"Crystal Prism Rain",
		"Levitation Energy Rings",
		"Dreamlike Double Exposure",
		"-Finish-"
	],

    "nsfwEffectList": [
		"-None-",
        "Cinematic sauna atmosphere",
        "Hyper-realistic glistening sweat",
        "X-Ray translucency",
        "Sticky oil texture",
        "Pheromone haze (pink mist)",
        "Soft-focus Vaseline lens blur",
        "Heat haze distortion",
        "Wet skin shader",
        "High-gloss latex shine",
        "Subsurface scattering (flushed skin)",
        "Bioluminescent tattoos",
        "Realistic rope burns",
        "Opaque milk-bath liquid",
        "Viscous slime dripping",
        "Heavy breathing condensation",
        "Ultraviolet blacklight body paint",
        "Tear-streaked mascara",
        "Goosebumps texture",
        "Natural flush gradient",
        "Cinematic film grain",
        "Tiny glowing butterflies of light",
        "Golden champagne bubbles",
        "Translucent bubbles of milk",
        "Liquid gold leaf fragments",
        "Soft pastel smoke",
        "Warm steam rising",
        "Tiny heart-shaped bokeh",
        "Micro-confetti of diamond dust",
        "Floating translucent veils",
        "Iridescent soap bubbles",
        "Thick cum droplets suspended mid-air",
		"Thick honey slowly dripping",
		"Shimmering pearl essence coating",
		"Neon body paint glowing streaks",
		"Translucent silk barely clinging",
		"Melting wax trails on skin",
		"Chromatic oil-slick sheen",
		"Steamy breath fogging glass",
		"Glittering micro-bead sweat",
		"Velvet rope imprints",
		"Condensation droplets racing down",
		"Metallic liquid chrome skin",
		"Soft latex second-skin gleam",
		"Rose-petal flush spreading",
		"Shivering gooseflesh ripples",
		"Silky ribbon bondage glow",
		"Whipped-cream slow cascade",
		"Glistening arousal close-up",
		"Iridescent bubble film popping",
		"Powdered sugar dusting",
		"Floating rose-gold sparkles",
		"Warm candle-wax accents",
		"Ethereal pheromone glow particles",
		"Crystal-clear lube strands",
		"Soft cashmere barely touching",
		"Steaming milk swirl around curves",
		"-Finish-"
	,
    ],

    "shotList": [
        "-None-",
        "intimate extreme close-up on eyes",
        "perfect full-body composition",
        "delicate waist-up portrait",
        "dramatic low-angle hero shot",
        "elegant three-quarter view",
        "romantic over-the-shoulder shot",
        "ethereal silhouette",
        "graceful kneeling pose",
        "dynamic dutch-tilt full body",
        "soft upper-body shot",
        "majestic wide shot",
        "intimate macro of hands",
        "cinematic profile view",
        "elegant back view",
        "poetic close-up of décolletage",
        "powerful worm’s-eye view",
        "serene overhead shot",
        "romantic medium shot",
        "regal throne shot",
        "dreamy extreme wide shot",
        "tender close-up",
        "dynamic action pose",
        "soft-focus portrait",
        "epic symmetrical composition",
        "gentle seated portrait",
        "intimate bed shot from above",
        "dramatic chiaroscuro",
        "elegant fashion-magazine cover",
        "fairytale storybook framing",
        "perfect rule-of-thirds",
		"extreme closeup",
        "macro detail shot",
        "tight closeup",
        "medium closeup",
        "closeup portrait",
        "head and shoulders",
        "bust shot",
        "waist shot",
        "cowboy shot",
        "medium shot",
        "medium full shot",
        "full body shot",
        "three-quarter body",
        "wide shot",
        "very wide shot",
        "extreme wide shot",
        "long establishing shot",
		"bokeh dreamscape",
		"long exposure silk",
		"golden hour glow",
		"blue hour twilight",
		"high-key minimal",
		"low-key dramatic",
		"forced perspective play",
		"leading line composition",
		"rule of thirds balance",
		"symmetrical reflection",
		"bird’s-eye overhead",
		"worm’s-eye dramatic angle",
		"silhouette silhouette",
		"light painting trails",
		"double exposure blend",
		"infrared surreal",
		"tilt-shift miniature",
		"panning motion blur",
		"framing within framing",
		"negative space isolation",
		"chiaroscuro drama",
		"rim light halo",
		"backlit translucence",
		"lens flare burst",
		"shallow depth slice",
		"deep depth expanse",
		"fish-eye distortion",
		"candid street moment",
		"environmental portrait",
		"headshot intensity",
		"levitation illusion",
		"smoke and mirrors",
		"prism refraction rainbow",
		"steel wool sparks",
		"water droplet refraction",
		"crystal ball inversion",
		"slow sync flash freeze",
		"zoom burst explosion",
        "-Finish-"
    ],

	"cameraLensList": [
		"-None-",
		"85mm creamy bokeh portrait lens",
		"50mm natural perspective",
		"35mm environmental storytelling lens",
		"135mm telephoto compression",
		"24mm dramatic wide-angle",
		"85mm f/1.2 razor-thin depth",
		"50mm f/1.4 dreamy glow",
		"35mm f/1.8 soft corners",
		"100mm macro intimate details",
		"24-70mm versatile zoom",
		"70-200mm beautiful compression",
		"prime 50mm classic look",
		"vintage Helios swirly bokeh",
		"anamorphic cinematic oval bokeh",
		"petzval lens artistic swirl",
		"tilt-shift miniature effect",
		"soft-focus dream lens",
		"ultra-sharp modern 85mm",
		"vignetting vintage lens",
		"cinematic 40mm pancake",
		"fish-eye dramatic curve",
		"58mm Noctilux buttery glow",
		"28mm wide street character",
		"200mm f/2 creamy telephoto",
		"Noct-Nikkor 58mm f/1.2 magic",
		"Leica 50mm Summilux velvet",
		"105mm f/1.4 bokeh monster",
		"Otus 55mm clinical sharpness",
		"85mm f/1.4 silky transition",
		"35mm f/1.4 cinematic soul",
		"135mm f/2 APO dream crusher",
		"Thambar 90mm soft romance",
		"Monochrom-only lens purity",
		"f/0.95 speed demon",
		"trioplan soap-bubble bokeh",
		"Meyer Görlitz 100mm glow",
		"Cooke look warm vintage",
		"Super-Takumar 50mm f/1.4 radioactive",
		"Zeiss 85mm f/1.4 Planar cream",
		"Voigtländer 35mm f/1.2 character king",
		"Sigma Art 40mm f/1.4 neutrality",
		"Canon 50mm f/1.0 L unicorn",
		"Nikon 50mm f/1.2 AIS classic",
		"Leica 75mm f/1.4 Summilux haze",
		"mirror lens donut bokeh",
		"Lensbaby velvet ethereal",
		"pancake 27mm tiny wonder",
		"28-70mm f/2 constant magic",
		"biogon 21mm wide perfection",
		"distagon 35mm three-dimensional",
		"-Finish-"
	],

	"lightingList": [
		"-None-",
		"dramatic golden-hour sunset",
		"soft volumetric god rays",
		"harsh neon cyberpunk pink and teal",
		"single overhead spotlight",
		"warm flickering candlelight",
		"cold blue moonlight",
		"crimson demonic rim-lighting",
		"soft pastel dawn light",
		"harsh white studio strobes",
		"gentle firefly glow",
		"golden cinematic lens flares",
		"deep teal and orange cyber-noir",
		"warm honey-colored rim light",
		"soft lavender fog",
		"dramatic chiaroscuro",
		"blood-red backlight",
		"ethereal bioluminescent underwater",
		"harsh overhead surgical light",
		"soft rosy bedroom lamp",
		"golden baroque chandelier light",
		"icy blue aurora borealis",
		"warm amber firelight",
		"neon purple club lighting",
		"soft golden renaissance window",
		"cold sterile white light",
		"warm steam-filled bathhouse light",
		"deep crimson hellfire",
		"soft peach sunrise",
		"harsh interrogation spotlight",
		"gentle candlelit gothic",
		"electric blue holographic light",
		"warm vintage Hollywood key light",
		"soft pink pheromone haze",
		"misty forest emerald glow",
		"hard midday desert sun",
		"buttery Rembrandt triangle",
		"cyan and magenta vaporwave",
		"warm tungsten practical lamps",
		"ghostly green ectoplasm light",
		"soft butterfly glamour lighting",
		"harsh sodium streetlight orange",
		"golden hour side-light sculpting",
		"cool overcast flat light",
		"blood-orange apocalyptic sky",
		"soft windowlight with venetian blinds",
		"purple-blacklight rave glow",
		"warm Edison bulb string lights",
		"cold clinical fluorescent hum",
		"dappled sunlight through leaves",
		"infernal orange lava glow",
		"soft diffused beauty dish",
		"electric magenta rim + teal fill",
		"warm 1940s film-noir key light",
		"icy cyan winter twilight",
		"golden sparkler light trails",
		"soft pastel cotton-candy sky",
		"harsh single bare bulb",
		"dreamy prismatic rainbow flares",
		"warm honeyed afternoon window",
		"deep violet twilight magic hour",
		"crisp arctic white side light",
		"soft rose-gold hour",
		"ominous green thunderstorm flash",
		"-Finish-"
	],
	"qualityList": [
		"-None-",
		"insane details, intricate linework, hypermaximalist masterpiece",
		"god-tier resolution, razor-sharp clarity, crystalline precision",
		"filigree carved by master artisans, baroque ornamentation, obsessive craftsmanship",
		"16k RAW perfection, 32k ultimate fidelity, breathtaking visual density",
		"flawless execution, museum-worthy grandeur, award-winning composition",
		"golden ratio perfection, divine proportions, mathematically perfect balance",
		"photorealistic masterpiece, hyperrealistic beyond belief, lifelike transcendence",
		"skin textured to perfection, microscopic pore detail, velvet-smooth realism",
		"individual hair strands rendered, flowing with natural luster, hyper-detailed fibers",
		"eyes with galactic depth, sparkling reflections, soul-piercing clarity",
		"musculature sculpted like classical statues, perfect anatomy, heroic definition",
		"dynamic heroic pose, cinematic motion frozen in time, epic action mastery",
		"volumetric godrays piercing the heavens, golden light shafts, divine illumination",
		"ethereal atmospheric haze, dreamy depth, cinematic environmental beauty",
		"dramatic chiaroscuro lighting, masterful contrast, Rembrandt-level shadows",
		"creamy bokeh masterpiece, buttery background blur, professional depth of field",
		"ray-traced reflections, mirror-like surfaces, physically accurate shine",
		"global illumination perfection, studio-quality lighting, flawless light bounce",
		"prismatic highlights exploding, radiant specular detail, luminous brilliance",
		"8k octane render perfection, unreal engine 6 realism, cinematic masterpiece",
		"microscopic surface imperfections, lifelike material authenticity, tactile realism",
		"subsurface scattering glow, translucent skin and petals, organic warmth",
		"perfect caustics dancing on water, refractive accuracy, liquid diamond",
		"atmospheric perspective mastery, infinite depth recession, painterly distance",
		"velvet micro-contrast, three-dimensional pop, sculpted by light itself",
		"lens breathing authenticity, gentle focus fall-off, living optical character",
		"film-grain elegance, 70mm IMAX grandeur, analog soul in digital form",
		"luminous color grading, Hollywood blockbuster palette, emotive tones",
		"every droplet and dust mote rendered, suspended in perfect stillness",
		"dynamic range beyond human vision, crushed blacks and blooming highlights",
		"silken fabric folds with individual threads, luxurious texture obsession",
		"breathtaking chromatic aberration control, zero distortion, optical nirvana",
		"sub-pixel sharpness, anti-aliased perfection, no artifact in sight",
		"cinematic anamorphic flares, oval bokeh galaxies, big-budget magic",
		"masterpiece symmetry with subtle asymmetry, intentional imperfection",
		"transcendent depth of field layering, foreground to infinity crisp",
		"light wrap and bounce so accurate it feels warm to look at",
		"award-winning National Geographic level detail, editorial perfection",
		"divine color science, calibrated to the soul, emotionally resonant tones",
		"-Finish-"
	],

	"handPositionList": [
		"-None-",
		"Hands on hips",
		"Arms crossed",
		"Hand resting on chin",
		"Finger on lips",
		"Adjusting hair",
		"Reaching towards camera",
		"Holding a weapon",
		"Clenched fists",
		"Hands in pockets",
		"Saluting",
		"Covering chest",
		"Hands behind head",
		"Resting hands on knees",
		"Holding a glowing orb",
		"Casting a spell",
		"Wiping sweat",
		"Adjusting glasses",
		"Prayer position at chest",
		"Hands framing face",
		"One hand in hair, one on hip",
		"Fingers interlaced behind back",
		"Jazz hands expressive",
		"Delicate fingertips touching lips",
		"Hand covering one eye",
		"Palms open in surrender",
		"Fingers forming a heart",
		"Pointing directly at viewer",
		"Hands cupping cheeks",
		"One hand on neck, vulnerable",
		"Fingers gently tracing collarbone",
		"Hands clasped in front",
		"Peace sign near face",
		"Hand resting on own shoulder",
		"Fingers splayed across chest",
		"Dramatic hair flip mid-motion",
		"Hands forming gun gesture",
		"Thumb hooked in pocket",
		"Waving softly",
		"Blowing a kiss",
		"Hands shielding eyes from light",
		"Fingers curled in beckoning",
		"One hand twirling hair strand",
		"Palms pressed together in namaste",
		"Hands sliding down thighs seductively",
		"Fingertips touching temples",
		"OK sign near eye",
		"Hands forming steeple",
		"Casual thumbs in belt loops",
		"-Finish-"
	],

	"subjectPositionList": [
		"-None-",
		"From below (Low Angle)",
		"From above (High Angle)",
		"Profile view",
		"Three-quarter view",
		"Back view",
		"Dutch Angle",
		"Overhead",
		"Sitting on a chair",
		"Kneeling on the floor",
		"Lying down",
		"Bent over",
		"Squatting",
		"Leaning against a wall",
		"Walking towards camera",
		"Floating in mid-air",
		"Arching back",
		"Sitting on edge of bed",
		"Reclining on sofa",
		"Lying on stomach, chin propped",
		"Kneeling with back to camera",
		"Standing with weight on one leg",
		"Lunging forward dramatically",
		"Crouching low",
		"Perched on stairs",
		"Leaning forward intensely",
		"Sitting cross-legged",
		"Standing in contrapposto",
		"Twisted torso, looking back",
		"One knee up, seated",
		"Hanging from above",
		"Dangling legs off ledge",
		"Backbend extreme",
		"Side-lying fetal curl",
		"On all fours",
		"Sprawled dramatically on floor",
		"Leaning out window",
		"Pressed against glass",
		"Emerging from water",
		"Suspended in zero gravity",
		"Walking away from camera",
		"Mid-jump frozen",
		"Climbing pose",
		"Yoga warrior pose",
		"Ballerina on pointe",
		"Dramatic hair toss turn",
		"Looking over shoulder seductively",
		"Crouched in fighting stance",
		"Sitting backward on chair",
		"Lying with arms above head",
		"Half-kneeling proposal pose",
		"-Finish-"
	],
};